// Package v1 Generated by lanai_cli codegen.
// Derived from contents in openapi contract, path: /apim/api/v1/keys
package v1

import (
	"context"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web/rest"
	apiv1 "cto-github.cisco.com/NFV-BU/test-service/pkg/api/v1"
	"go.uber.org/fx"
)

type KeysController struct{}

type keysControllerDI struct {
	fx.In
}

func NewKeysController(di keysControllerDI) web.Controller {
	return &KeysController{}
}

func (c *KeysController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("keys-get").
			Get("/api/v1/keys").
			EndpointFunc(c.SearchApiKeys).
			Build(),
	}
}

func (c *KeysController) SearchApiKeys(ctx context.Context, req apiv1.SearchApiKeysRequest) (interface{}, error) {
	return nil, nil
}
