// Package v1 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from contents in openapi contract, path: /my/api/v1/requestBodyTests/{id}
package v1

import (
	"context"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web/rest"
	apiv1 "cto-github.cisco.com/NFV-BU/test-service/pkg/api/v1"
	"go.uber.org/fx"
)

type RequestBodyTestsIdController struct{}

type requestBodyTestsIdControllerDI struct {
	fx.In
}

func NewRequestBodyTestsIdController(di requestBodyTestsIdControllerDI) web.Controller {
	return &RequestBodyTestsIdController{}
}

func (c *RequestBodyTestsIdController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("requestbodytests-id-delete").
			Delete("/api/v1/requestBodyTests/:id").
			EndpointFunc(c.TestStringRequestBody).
			Build(),
		rest.
			New("requestbodytests-id-get").
			Get("/api/v1/requestBodyTests/:id").
			EndpointFunc(c.TestRequestBodyWithAdditionalProperties).
			Build(),
		rest.
			New("requestbodytests-id-patch").
			Patch("/api/v1/requestBodyTests/:id").
			EndpointFunc(c.PatchTestPath).
			Build(),
		rest.
			New("requestbodytests-id-post").
			Post("/api/v1/requestBodyTests/:id").
			EndpointFunc(c.UpdateServiceStatus).
			Build(),
		rest.
			New("requestbodytests-id-put").
			Put("/api/v1/requestBodyTests/:id").
			EndpointFunc(c.PutTestPath).
			Build(),
	}
}

func (c *RequestBodyTestsIdController) TestStringRequestBody(ctx context.Context, req apiv1.TestStringRequestBodyRequest) (interface{}, error) {
	return nil, nil
}

func (c *RequestBodyTestsIdController) TestRequestBodyWithAdditionalProperties(ctx context.Context, req apiv1.TestRequestBodyWithAdditionalPropertiesRequest) (interface{}, error) {
	return nil, nil
}

func (c *RequestBodyTestsIdController) PatchTestPath(ctx context.Context, req apiv1.PatchTestPathRequest) (interface{}, error) {
	return nil, nil
}

func (c *RequestBodyTestsIdController) UpdateServiceStatus(ctx context.Context, req apiv1.UpdateServiceStatusRequest) (interface{}, error) {
	return nil, nil
}

func (c *RequestBodyTestsIdController) PutTestPath(ctx context.Context, req apiv1.PutTestPathRequest) (interface{}, error) {
	return nil, nil
}
