// Generated by lanai_cli codegen. DO NOT EDIT
package v1

import (
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	v1 "cto-github.cisco.com/NFV-BU/test-service/pkg/service/v1"
	"go.uber.org/fx"
)

type TestpathScopeController struct {
	testpathScopeService v1.TestpathScopeService
}

type testpathScopeControllerDI struct {
	fx.In
	TestpathScopeService v1.TestpathScopeService
}

func NewTestpathScopeController(di testpathScopeControllerDI) web.Controller {
	return &TestpathScopeController{
		testpathScopeService: di.TestpathScopeService,
	}
}

func (c *TestpathScopeController) Mappings() []web.Mapping {
	return []web.Mapping{}
}
