repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: go-lanai

  # A short description of the repository that will show up on GitHub
  description: go-lanai is a set of application frameworks and modules that make writing applications (especially micro-services) easy

  # A URL with more information about the repository
  # homepage: 

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: false

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams:
  - name: org-admins
    # The permission to grant the team. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
    # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
    permission: admin

  - name: go-lanai-admins
    permission: admin

  - name: go-lanai-maintainers
    permission: maintain

  - name: go-lanai
    permission: triage

# Collaborators: give specific users access to this repository.
# See https://docs.github.com/en/rest/reference/collaborators for available options
collaborators: []
