// Package v1 Generated by lanai-cli codegen. DO NOT EDIT
// Derived from path: /my/api/v1/requestBodyTests/{id}
package v1

import (
	"encoding/json"
	"github.com/cisco-open/test-service/pkg/api"
	"github.com/google/uuid"
)

type TestStringRequestBodyRequest struct {
	Id   string  `uri:"id" binding:"required,uuid"`
	Body *string `json:"-" binding:"required"`
}

func (t *TestStringRequestBodyRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t TestStringRequestBodyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type TestRequestBodyWithAdditionalPropertiesRequest struct {
	Id     string                 `uri:"id" binding:"required,uuid"`
	Values map[string]interface{} `json:"-"`
}

type PatchTestPathRequest struct {
	Id   string      `uri:"id" binding:"required,uuid"`
	Body []uuid.UUID `json:"-" binding:"required,min=1,dive,uuid"`
}

func (t *PatchTestPathRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t PatchTestPathRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type UpdateServiceStatusRequest struct {
	Id   string              `uri:"id" binding:"required,uuid"`
	Body []api.GenericObject `json:"-" binding:"required,min=1"`
}

func (t *UpdateServiceStatusRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t UpdateServiceStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type PutTestPathRequest struct {
	Id string `uri:"id" binding:"required,uuid"`
	api.GenericObject
}
