// Package v2 Generated by lanai-cli codegen.
// Derived from contents in openapi contract, path: /my/api/v2/testArrayUUID
package v2

import (
    "context"
    apiv2 "cto-github.cisco.com/NFV-BU/test-service/pkg/api/v2"
    "github.com/cisco-open/go-lanai/pkg/web"
    "github.com/cisco-open/go-lanai/pkg/web/rest"
    "go.uber.org/fx"
)

type TestArrayUUIDController struct{}

type testArrayUUIDControllerDI struct {
	fx.In
}

func NewTestArrayUUIDController(di testArrayUUIDControllerDI) web.Controller {
	return &TestArrayUUIDController{}
}

func (c *TestArrayUUIDController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("testarrayuuid-get").
			Get("/api/v2/testArrayUUID").
			EndpointFunc(c.TestUUIDInArray).
			Build(),
		rest.
			New("testarrayuuid-put").
			Put("/api/v2/testArrayUUID").
			EndpointFunc(c.TestRequestBodyWithAllOf).
			Build(),
	}
}

func (c *TestArrayUUIDController) TestUUIDInArray(ctx context.Context, req apiv2.TestUUIDInArrayRequest) (interface{}, error) {
	return nil, nil
}

func (c *TestArrayUUIDController) TestRequestBodyWithAllOf(ctx context.Context, req apiv2.TestRequestBodyWithAllOfRequest) (interface{}, error) {
	return nil, nil
}
