// Package controller Generated by lanai-cli codegen. DO NOT EDIT
package controller

import (
	controllerv1 "cto-github.cisco.com/NFV-BU/go-lanai/examples/skeleton-service/pkg/controller/v1"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/bootstrap"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/utils/validation"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	"github.com/go-playground/validator/v10/non-standard/validators"
	"go.uber.org/fx"
)

var Module = &bootstrap.Module{
	Name:       "controller",
	Precedence: bootstrap.AnonymousModulePrecedence,
	Options: []fx.Option{
		fx.Invoke(register),
	},
}

var SubModules = []*bootstrap.Module{
	controllerv1.Module,
}

func Use() {
	bootstrap.Register(Module)
	for _, m := range SubModules {
		bootstrap.Register(m)
	}
}

func register(lc fx.Lifecycle, r *web.Registrar) {
	// validation, note, related validation translations are registered in errorhandling package
	_ = web.Validator().RegisterValidation("notblank", validators.NotBlank)
	_ = web.Validator().RegisterValidation("enumof", validation.CaseInsensitiveOneOf())
}
