# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.10.0

jobs:
  test_and_verify:
#    executor:
#      name: go/default
#      tag: '1.21-node'
    docker:
      - image: cimg/go:1.21-node
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      - run: "make init"
      - go/save-cache # Save Go modules to cache.
      - run:
          name: "Run Tests"
          command: "make test"
      - run:
          name: "Static Code Analysis"
          command: "make lint"
      - run:
          name: "Make Report"
          command: "make report"
  noop:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo noop

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  manual_verify:
    when:
      equal: [ "api", << pipeline.trigger_source >> ] # Only triggered by API/UI
    jobs:
      - test_and_verify:
          name: "Test and Verify"
          pre-steps:
            - run: echo Triggered by << pipeline.trigger_parameters.circleci.actor_id >>
          post-steps:
            - store_test_results:
                path: dist/junit-report.xml
  auto_verify:
    when:
      not:
        equal: [ "api", << pipeline.trigger_source >> ]
    jobs:
      - test_and_verify:
          type: approval

  verify_pr:
    when:
      and:
        - matches:
            pattern: "^pull_request$"
            value: << pipeline.trigger_parameters.circleci.event_type >>
        - false # We currently disable this workflows
    jobs:
      - test_and_verify

