// Package v4 Generated by lanai_cli codegen.
// Derived from contents in openapi contract, path: /my/api/v4/testAPIThatDoesntUseAnyImports
package v4

import (
	"context"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web/rest"
	"go.uber.org/fx"
)

type TestAPIThatDoesntUseAnyImportsController struct{}

type testAPIThatDoesntUseAnyImportsControllerDI struct {
	fx.In
}

func NewTestAPIThatDoesntUseAnyImportsController(di testAPIThatDoesntUseAnyImportsControllerDI) web.Controller {
	return &TestAPIThatDoesntUseAnyImportsController{}
}

func (c *TestAPIThatDoesntUseAnyImportsController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("testapithatdoesntuseanyimports-post").
			Post("/api/v4/testAPIThatDoesntUseAnyImports").
			EndpointFunc(c.CreateDevice).
			Build(),
	}
}

func (c *TestAPIThatDoesntUseAnyImportsController) CreateDevice(ctx context.Context) (interface{}, error) {
	return nil, nil
}
