// Package controller Generated by lanai-cli codegen. DO NOT EDIT
package controller

import (
	"github.com/cisco-open/go-lanai/pkg/bootstrap"
	"github.com/cisco-open/go-lanai/pkg/utils/validation"
	"github.com/cisco-open/go-lanai/pkg/web"
	controllerv1 "github.com/cisco-open/test-service/pkg/controller/v1"
	controllerv2 "github.com/cisco-open/test-service/pkg/controller/v2"
	controllerv3 "github.com/cisco-open/test-service/pkg/controller/v3"
	controllerv4 "github.com/cisco-open/test-service/pkg/controller/v4"
	"github.com/go-playground/validator/v10/non-standard/validators"
	"go.uber.org/fx"
)

var Module = &bootstrap.Module{
	Name:       "controller",
	Precedence: bootstrap.AnonymousModulePrecedence,
	Options: []fx.Option{
		fx.Invoke(register),
	},
}

var SubModules = []*bootstrap.Module{
	controllerv1.Module,
	controllerv2.Module,
	controllerv3.Module,
	controllerv4.Module,
}

func Use() {
	bootstrap.Register(Module)
	for _, m := range SubModules {
		bootstrap.Register(m)
	}
}

func register(lc fx.Lifecycle, r *web.Registrar) {
	// validation, note, related validation translations are registered in errorhandling package
	_ = web.Validator().RegisterValidation("notblank", validators.NotBlank)
	_ = web.Validator().RegisterValidation("enumof", validation.CaseInsensitiveOneOf())
	_ = web.Validator().RegisterValidationCtx("date-time", validation.Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[\\+-]\\d{2}:\\d{2})?$"))
	_ = web.Validator().RegisterValidationCtx("uuid", validation.Regex("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"))
	_ = web.Validator().RegisterValidationCtx("regexA217A", validation.Regex("^[a-zA-Z0-9\\_\\-\\.\\@]{1,128}$"))
	_ = web.Validator().RegisterValidationCtx("regexEFF6B", validation.Regex("allOfExclusiveFormat"))
	_ = web.Validator().RegisterValidationCtx("date", validation.Regex("^\\d{4}-\\d{2}-\\d{2}$"))
	_ = web.Validator().RegisterValidationCtx("regex50C92", validation.Regex("^[a-zA-Z0-8-_=]{1,256}$"))
	_ = web.Validator().RegisterValidationCtx("regexA2EFE", validation.Regex("^[a-zA-Z0-9-_=]{1,256}$"))
	_ = web.Validator().RegisterValidationCtx("regex2F1C0", validation.Regex("^$|^[Aa][Ss][Cc]|[Dd][Ee][Ss][Cc]$"))
	_ = web.Validator().RegisterValidationCtx("regex78135", validation.Regex("^[a-zA-Z0-5-_=]{1,256}$"))
	_ = web.Validator().RegisterValidationCtx("regex440F7", validation.Regex("^[a-zA-Z0-7-_=]{1,256}$"))
}
