// Package v1 Generated by lanai-cli codegen.
// Derived from contents in openapi contract, path: /my/api/v1/controllerResponsesTest
package v1

import (
	"context"
	"github.com/cisco-open/go-lanai/pkg/web"
	"github.com/cisco-open/go-lanai/pkg/web/rest"
	"github.com/cisco-open/test-service/pkg/api"
	apiv1 "github.com/cisco-open/test-service/pkg/api/v1"
	"go.uber.org/fx"
)

type ControllerResponsesTestController struct{}

type controllerResponsesTestControllerDI struct {
	fx.In
}

func NewControllerResponsesTestController(di controllerResponsesTestControllerDI) web.Controller {
	return &ControllerResponsesTestController{}
}

func (c *ControllerResponsesTestController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("controllerresponsestest-delete").
			Delete("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestResponseObjectResponse).
			Build(),
		rest.
			New("controllerresponsestest-get").
			Get("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestCommonObjectArrayResponse).
			Build(),
		rest.
			New("controllerresponsestest-head").
			Head("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestNoResponse).
			Build(),
		rest.
			New("controllerresponsestest-patch").
			Patch("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestStringArrayResponse).
			Build(),
		rest.
			New("controllerresponsestest-put").
			Put("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestCommonObjectResponse).
			Build(),
		rest.
			New("controllerresponsestest-trace").
			Trace("/api/v1/controllerResponsesTest").
			EndpointFunc(c.TestStringResponse).
			Build(),
	}
}

func (c *ControllerResponsesTestController) TestResponseObjectResponse(ctx context.Context) (*apiv1.TestResponseObjectResponseResponse, error) {
	return &apiv1.TestResponseObjectResponseResponse{}, nil
}

func (c *ControllerResponsesTestController) TestCommonObjectArrayResponse(ctx context.Context) (interface{}, error) {
	return nil, nil
}

func (c *ControllerResponsesTestController) TestNoResponse(ctx context.Context) (interface{}, error) {
	return nil, nil
}

func (c *ControllerResponsesTestController) TestStringArrayResponse(ctx context.Context) (interface{}, error) {
	return nil, nil
}

func (c *ControllerResponsesTestController) TestCommonObjectResponse(ctx context.Context) (*api.GenericObject, error) {
	return &api.GenericObject{}, nil
}

func (c *ControllerResponsesTestController) TestStringResponse(ctx context.Context) (string, error) {
	return "", nil
}
