# Copyright 2023 Cisco Systems, Inc. and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

security:
  cors:
    enabled: true
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: ""
    allow-credentials: false
    max-age: 12h
  cache: # security related cache - currently just for tenant hierarchy data
    db-index: 2
  session:
    idle-timeout: "2h"
    absolute-timeout: "4h"
    max-concurrent-sessions: 2
    db-index: 8
  timeout-support:
    db-index: ${security.session.db-index}