// Package v1 Generated by lanai-cli codegen. DO NOT EDIT
// Derived from path: /apim/api/v1/keys
package v1

type SearchApiKeysRequest struct {
	StringParamThatZeroValueIsValidFor string `form:"StringParamThatZeroValueIsValidFor" binding:"omitempty,regexD4EC2,max=32"`
}
