// Package v1 Generated by lanai-cli codegen. DO NOT EDIT
// Derived from path: /my/api/v1/testpath/{scope}
package v1

import (
	"github.com/cisco-open/test-service/pkg/api"
)

type DeleteTestPathRequest struct {
	Scope     string `uri:"scope" binding:"required,regex78135"`
	TestParam string `form:"testParam" binding:"omitempty,max=128"`
}

type DeleteTestPathResponse struct {
	Id string `json:"id"`
	api.GenericResponse
}

type TestpathScopeGetRequest struct {
	Scope        string `uri:"scope" binding:"required,regex78135"`
	HEADER_PARAM bool   `header:"HEADER-PARAM"`
}

type TestpathScopePatchRequest struct {
	Scope         string `uri:"scope"`
	QueryDefault  string `form:"queryDefault,default=defaultQuery"`
	HeaderDefault string `header:"headerDefault,default=defaultHeader"`
}

type PostTestPathRequest struct {
	Scope string `uri:"scope" binding:"required,regex440F7"`
}
