swagger:
  spec: configs/api-doc.json
  security:
    secure-docs: true
    sso:
      base-url: http://localhost:8900/auth
      token-path: /v2/token
      authorize-path: /v2/authorize
      client-id: nfv-client
      #client-secret: nfv-secret
      additional-params:
        - name: tenant_id
          display-name: Tenant Id
#         candidate-source-url:
#         candidate-json-path:
