ARG BASE_IMAGE=dockerhub.cisco.com/vms-platform-dev-docker/msx-base-buster:4.1.0-92

## Build Container ##
FROM dockerhub.cisco.com/vms-platform-dev-docker/golang:1.16.3 AS builder
ARG PRIVATE_MODS
ARG VERSION
ARG GITKEY
WORKDIR /go/src/
ADD . /go/src/
RUN mkdir -p -m 0600 ~/.ssh && \
    echo "StrictHostKeyChecking no " > /root/.ssh/config && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts && \
    echo "Host cto-github.cisco.com" >> ~/.ssh/config  && \
    echo "              HostName cto-github.cisco.com" >> ~/.ssh/config  && \
    echo "              User git" >> ~/.ssh/config  && \
    echo "             IdentityFile /root/github.key" >> ~/.ssh/config
COPY ${GITKEY} /root/github.key
RUN chmod 600 /root/github.key
RUN make init-once init-cli drop-replace; \
    make clean build PRIVATE_MODS="$PRIVATE_MODS" VERSION="$VERSION"

## Distribution Container ##
FROM ${BASE_IMAGE}
{{- range $_, $elem := .Executables }}
{{- if gt $elem.Port 0 }}
EXPOSE {{ $elem.Port }}
{{- end }}
{{- end }}
WORKDIR /service/
COPY build/package/dockerlaunch.sh /service/dockerlaunch.sh
RUN chmod 755 /service/dockerlaunch.sh
COPY --from=builder /go/src/dist /service
ENTRYPOINT ["/service/dockerlaunch.sh"]