// Generated by lanai_cli codegen. DO NOT EDIT
package v3

import (
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	v3 "cto-github.cisco.com/NFV-BU/test-service/pkg/service/v3"
	"go.uber.org/fx"
)

type AnotherTestController struct {
	anotherTestService v3.AnotherTestService
}

type anotherTestControllerDI struct {
	fx.In
	AnotherTestService v3.AnotherTestService
}

func NewAnotherTestController(di anotherTestControllerDI) web.Controller {
	return &AnotherTestController{
		anotherTestService: di.AnotherTestService,
	}
}

func (c *AnotherTestController) Mappings() []web.Mapping {
	return []web.Mapping{}
}
