// Generated by lanai_cli codegen. DO NOT EDIT
package v3

import (
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/bootstrap"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
)

func Use() {
	bootstrap.AddOptions(
		web.FxControllerProviders(
			NewAnotherTestController,
		),
	)
}
