// Package v1 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from path: /my/api/v1/controllerResponsesTest
package v1

type TestResponseObjectResponseResponse struct {
	FirstProperty  int    `json:"firstProperty"`
	SecondProperty string `json:"secondProperty"`
}
