// Package v1 Generated by lanai-cli codegen. DO NOT EDIT
// Derived from path: /my/api/v1/uuidtest/{id}
package v1

type TestUUIDInPathParamRequest struct {
	Id string `uri:"id" binding:"required,uuid"`
}
