if(!window["dojoConfig"]){
	var dojoConfig = {
		baseUrl: "vendor",
		async: true,
		extraLocale: [
		]
	};
	if(!window["dojox"]){
		var dojox = {};
	}
}

//>>built
(function(b,m){var h,k,e,c,n=function(){return"undefined"!==typeof w&&"function"!==typeof w?w:"undefined"!==typeof window?window:"undefined"!==typeof self?self:this}(),a=function(){},g=function(B){for(var a in B)return 0;return 1},d={}.toString,f=function(B){return"[object Function]"==d.call(B)},r=function(B){return"[object String]"==d.call(B)},l=function(B){return"[object Array]"==d.call(B)},C=function(B,a){if(B)for(var d=0;d<B.length;)a(B[d++])},u=function(B,a){for(var d in a)B[d]=a[d];return B},
x=function(B,a){return u(Error(B),{src:"dojoLoader",info:a})},z=1,y=function(){return"_"+z++},t=function(a,d,c){return Ea(a,d,c,0,t)},w=n,A=w.document,E=A&&A.createElement("DiV"),q=t.has=function(a){return f(p[a])?p[a]=p[a](w,A,E):p[a]},p=q.cache=m.hasCache;f(b)&&(b=b(n));q.add=function(a,d,c,f){(void 0===p[a]||f)&&(p[a]=d);return c&&q(a)};q.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);q("host-webworker")&&(u(m.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,
"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1,"dojo-guarantee-console":0}),m.loaderPatch={injectUrl:function(a,d){try{importScripts(a),d()}catch(Da){console.error(Da)}}});for(var J in b.has)q.add(J,b.has[J],0,1);var v=0,F=[],D=0,M=a,S=a,ga;t.isXdUrl=a;t.initSyncLoader=function(a,d,c){D||(D=a,M=d,S=c);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:F,modules:H,execQ:K,getModule:N,injectModule:ha,setArrived:T,signal:Q,finishExec:W,execModule:X,dojoRequirePlugin:D,
getLegacyMode:function(){return v},guardCheckComplete:Y}};var Xa=location.protocol,Fa=location.host;t.isXdUrl=function(a){return/^\./.test(a)?!1:/^\/\//.test(a)?!0:(a=a.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(a[1]!=Xa||Fa&&a[2]!=Fa)};q.add("dojo-force-activex-xhr",!A.addEventListener&&"file:"==window.location.protocol);q.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(q("native-xhr")&&!q("dojo-force-activex-xhr"))ga=function(){return new XMLHttpRequest};else{var I=["Msxml2.XMLHTTP","Microsoft.XMLHTTP",
"Msxml2.XMLHTTP.4.0"],G;for(c=0;3>c;)try{G=I[c++];new ActiveXObject(G);break}catch(B){}ga=function(){return new ActiveXObject(G)}}t.getXhr=ga;q.add("dojo-gettext-api",1);t.getText=function(a,d,c){var B=ga();B.open("GET",ia(a),!1);B.send(null);if(200==B.status||!location.host&&!B.status)c&&c(B.responseText,d);else throw x("xhrFailed",B.status);return B.responseText};var R=q("csp-restrictions")?function(){}:new Function("return eval(arguments[0]);");t.eval=function(a,d){return R(a+"\r\n//# sourceURL\x3d"+
d)};var O={},Q=t.signal=function(a,d){var c=O[a];C(c&&c.slice(0),function(a){a.apply(null,l(d)?d:[d])})},Ya=t.on=function(a,d){var c=O[a]||(O[a]=[]);c.push(d);return{remove:function(){for(var a=0;a<c.length;a++)if(c[a]===d){c.splice(a,1);break}}}},Ga=[],Za={},Ha=[],Z={},Ia=t.map={},ja=[],H={},ta="",P={},ka={},ua={},la=0;if(!q("foreign-loader"))var ma=function(a,d){d=!1!==d;var c,B,f,b;for(c in ka)B=ka[c],(f=c.match(/^url\:(.+)/))?P["url:"+Ja(f[1],a)]=B:"*now"==c?b=B:"*noref"!=c&&(f=aa(c,a,!0),P[f.mid]=
P["url:"+f.url]=B);b&&b(va(a));d&&(ka={})};var Ka=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},wa=function(a,d){d.splice(0,d.length);for(var c in a)d.push([c,a[c],new RegExp("^"+Ka(c)+"(/|$)"),c.length]);d.sort(function(a,d){return d[3]-a[3]});return d},$a=function(a,d){C(a,function(a){d.push([r(a[0])?new RegExp("^"+Ka(a[0])+"$"):a[0],a[1]])})},La=function(a){var d=a.name;d||(d=a,a={name:d});a=u({main:"main"},a);a.location=a.location?a.location:d;a.packageMap&&
(Ia[d]=a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));Z[d]=a},Ma=[],ba=function(a,d,c){for(var f in a){"waitSeconds"==f&&(t.waitms=1E3*(a[f]||0));"cacheBust"==f&&(ta=a[f]?r(a[f])?a[f]:(new Date).getTime()+"":"");if("baseUrl"==f||"combo"==f)t[f]=a[f];if("async"==f){var b=a[f];t.legacyMode=v=r(b)&&/sync|legacyAsync/.test(b)?b:b?!1:"sync";t.async=!v}a[f]!==p&&(t.rawConfig[f]=a[f],"has"!=f&&q.add("config-"+f,a[f],0,d))}t.baseUrl||(t.baseUrl="./");/\/$/.test(t.baseUrl)||(t.baseUrl+="/");
for(f in a.has)q.add(f,a.has[f],0,d);C(a.packages,La);for(var g in a.packagePaths)C(a.packagePaths[g],function(a){var d=g+"/"+a;r(a)&&(a={name:a});a.location=d;La(a)});wa(u(Ia,a.map),ja);C(ja,function(a){a[1]=wa(a[1],[]);"*"==a[0]&&(ja.star=a)});wa(u(Za,a.paths),Ha);$a(a.aliases,Ga);if(!q("foreign-loader")){if(d)Ma.push({config:a.config});else for(f in a.config)d=N(f,c),d.config=u(d.config||{},a.config[f]);a.cache&&(ma(),ka=a.cache,ma(0,!!a.cache["*noref"]))}Q("config",[a,t.rawConfig])};t.rawConfig=
{};ba(m,1);ba(b,1);ba(ua,1);if(!q("foreign-loader"))var ca=function(a){Y(function(){C(a.deps,ha)})},Ea=function(d,c,f,b,g){var e;if(r(d)){if((e=N(d,b,!0))&&e.executed)return e.result;throw x("undefinedModule",d);}l(d)||(ba(d,0,b),d=c,c=f);if(l(d))if(d.length){f="require*"+y();for(var k,p=[],B=0;B<d.length;)k=d[B++],p.push(N(k,b));e=u(na("",f,0,""),{injected:2,deps:p,def:c||a,require:b?b.require:t,gc:1});H[e.mid]=e;ca(e);var n=da&&"sync"!=v;Y(function(){X(e,n)});e.executed||K.push(e);U()}else c&&c();
return g},va=function(a){if(!a)return t;var d=a.require;d||(d=function(c,f,b){return Ea(c,f,b,a,d)},a.require=u(d,t),d.module=a,d.toUrl=function(d){return Ja(d,a)},d.toAbsMid=function(d){return xa(d,a)},d.syncLoadNls=function(d){d=aa(d,a);var c=H[d.mid];if(!c||!c.executed)if(V=P[d.mid]||P["url:"+d.url])oa(V),c=H[d.mid];return c&&c.executed&&c.result});return d},K=[],pa=[],L={},bb=function(a){a.injected=1;L[a.mid]=1;a.url&&(L[a.url]=a.pack||1);ab()},T=function(a){a.injected=2;delete L[a.mid];a.url&&
delete L[a.url];g(L)&&(cb(),"xd"==v&&(v="sync"))},db=t.idle=function(){return!pa.length&&g(L)&&!K.length&&!da};var qa=function(a,d){if(d)for(var c=0;c<d.length;c++)if(d[c][2].test(a))return d[c];return 0},Na=function(a){var d=[],c,f;for(a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&d.length&&".."!=f?(d.pop(),f=d[d.length-1]):"."!=c&&d.push(f=c);return d.join("/")},na=function(a,d,c,f){var b=t.isXdUrl(f);return{pid:a,mid:d,pack:c,url:f,executed:0,def:0,isXd:b,isAmd:!!(b||Z[a]&&Z[a].isAmd)}},
Oa=function(a,d,c,b,g,e,l,k,p,r){var n,D,q,v;v=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||v&&!d)return na(0,a,0,a);a=Na(v?d.mid+"/../"+a:a);if(/^\./.test(a))throw x("irrationalPath",a);r||v||!e.star||(q=qa(a,e.star[1]));!q&&d&&(q=(q=qa(d.mid,e))&&qa(a,q[1]));q&&(a=q[1]+a.substring(q[3]));d=(h=a.match(/^([^\/]+)(\/(.+))?$/))?h[1]:"";(n=c[d])?a=d+"/"+(D=h[3]||n.main):d="";var B=0;C(k,function(d){var c=a.match(d[0]);c&&0<c.length&&(B=f(d[1])?a.replace(d[0],d[1]):d[1])});if(B)return Oa(B,0,c,b,g,
e,l,k,p);if(c=b[a])return p?na(c.pid,c.mid,c.pack,c.url):b[a];b=(q=qa(a,l))?q[1]+a.substring(q[3]):d?("/"===n.location.slice(-1)?n.location.slice(0,-1):n.location)+"/"+D:a;/(^\/)|(\:)/.test(b)||(b=g+b);return na(d,a,n,Na(b+".js"))},aa=function(a,d,c){return Oa(a,d,Z,H,t.baseUrl,ja,Ha,Ga,void 0,c)};if(!q("foreign-loader"))var Pa=function(a,d,c){return a.normalize?a.normalize(d,function(a){return xa(a,c)}):xa(d,c)},Qa=0,N=function(a,d,c){var f,b;(f=a.match(/^(.+?)\!(.*)$/))?(b=N(f[1],d,c),"sync"!=v||
b.executed||(ha(b),2!==b.injected||b.executed||Y(function(){X(b)}),b.executed?ra(b):K.unshift(b)),5!==b.executed||b.load||ra(b),b.load?(f=Pa(b,f[2],d),a=b.mid+"!"+(b.dynamic?++Qa+"!":"")+f):(f=f[2],a=b.mid+"!"+ ++Qa+"!waitingForPlugin"),a={plugin:b,mid:a,req:va(d),prid:f}):a=aa(a,d);return H[a.mid]||!c&&(H[a.mid]=a)};var xa=t.toAbsMid=function(a,d){return aa(a,d).mid},Ja=t.toUrl=function(a,d){var c=aa(a+"/x",d),f=c.url;return ia(0===c.pid?a:f.substring(0,f.length-5))};if(!q("foreign-loader"))var Ra=
{injected:2,executed:5,def:3,result:3},ya=function(a){return H[a]=u({mid:a},Ra)},eb=ya("require"),fb=ya("exports"),gb=ya("module"),sa={},za=0,ra=function(a){var d=a.result;a.dynamic=d.dynamic;a.normalize=d.normalize;a.load=d.load;return a},hb=function(a){var d={};C(a.loadQ,function(c){var f=Pa(a,c.prid,c.req.module),b=a.dynamic?c.mid.replace(/waitingForPlugin$/,f):a.mid+"!"+f,f=u(u({},c),{mid:b,prid:f,injected:0});H[b]&&H[b].injected||Sa(H[b]=f);d[c.mid]=H[b];T(c);delete H[c.mid]});a.loadQ=0;var c=
function(a){for(var c=a.deps||[],f=0;f<c.length;f++)(a=d[c[f].mid])&&(c[f]=a)},f;for(f in H)c(H[f]);C(K,c)},W=function(a){t.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=za++;C(a.provides,function(a){a()});a.loadQ&&(ra(a),hb(a));for(c=0;c<K.length;)K[c]===a?K.splice(c,1):c++;/^require\*/.test(a.mid)&&delete H[a.mid]},ib=[],X=function(a,d){if(4===a.executed)return t.trace("loader-circular-dependency",[ib.concat(a.mid).join("-\x3e")]),!a.def||d?sa:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return sa;
var c=a.mid,b=a.deps||[],g,e=[],l=0;for(a.executed=4;g=b[l++];){g=g===eb?va(a):g===fb?a.cjs.exports:g===gb?a.cjs:X(g,d);if(g===sa)return a.executed=0,t.trace("loader-exec-module",["abort",c]),sa;e.push(g)}t.trace("loader-run-factory",[a.mid]);c=a.def;F.unshift(a);e=f(c)?c.apply(null,e):c;a.result=void 0===e&&a.cjs?a.cjs.exports:e;F.shift(a);W(a)}return a.result},da=0,Y=function(a){try{da++,a()}catch(Wa){throw Wa;}finally{da--}db()&&Q("idle",[])},U=function(){da||Y(function(){M();for(var a,d,c=0;c<
K.length;)a=za,d=K[c],X(d),a!=za?(M(),c=0):c++})};var ia="function"==typeof b.fixupUrl?b.fixupUrl:function(a){a+="";return a+(ta?(/\?/.test(a)?"\x26":"?")+ta:"")},Sa=function(a){var d=a.plugin;5!==d.executed||d.load||ra(d);var c=function(d){a.result=d;T(a);W(a);U()};d.load?d.load(a.prid,a.req,c):d.loadQ?d.loadQ.push(a):(d.loadQ=[a],K.unshift(d),ha(d))},V=0,ea=0,Aa=0,oa=function(a,d){Aa=1;a===V?V.call(null):t.eval(a,d.mid);Aa=0},ha=function(a){var d=a.mid,c=a.url;if(!(a.executed||a.injected||L[d]||
a.url&&(a.pack&&L[a.url]===a.pack||1==L[a.url])))if(bb(a),a.plugin)Sa(a);else{var f=function(){Ta(a);if(2!==a.injected){if(q("dojo-enforceDefine")){Q("error",x("noDefine",a));return}T(a);u(a,Ra);t.trace("loader-define-nonmodule",[a.url])}v?!F.length&&U():U()};if(V=P[d]||P["url:"+a.url])t.trace("loader-inject",["cache",a.mid,c]),oa(V,a),f();else{if(v)if(a.isXd)"sync"==v&&(v="xd");else if(!a.isAmd||"sync"==v){t.trace("loader-inject",["xhr",a.mid,c,"sync"!=v]);t.getText(c,"sync"!=v,function(b){if("sync"==
v){F.unshift(a);oa(b,a);F.shift();Ta(a);a.cjs||(T(a),W(a));if(a.finish){b=d+"*finish";var g=a.finish;delete a.finish;fa(b,["dojo",("dojo/require!"+g.join(",")).replace(/\./g,"/")],function(a){C(g,function(d){a.require(d)})});K.unshift(N(b))}f()}else(b=S(a,b))?(oa(b,a),f()):(ea=a,t.injectUrl(ia(c),f,a),ea=0)});return}t.trace("loader-inject",["script",a.mid,c]);ea=a;t.injectUrl(ia(c),f,a);ea=0}}},Ba=function(a,d,c){t.trace("loader-define-module",[a.mid,d]);var b=a.mid;if(2===a.injected)return Q("error",
x("multipleDefine",a)),a;u(a,{deps:d,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(d){a.cjs.exports=d},config:function(){return a.config}}});for(var g=0;d[g];g++)d[g]=N(d[g],a);v&&!L[b]&&(ca(a),K.push(a),U());T(a);f(c)||d.length||(a.result=c,W(a));return a},Ta=function(a,d){for(var c=[],f,b;pa.length;)b=pa.shift(),d&&(b[0]=d.shift()),f=b[0]&&N(b[0])||a,c.push([f,b[1],b[2]]);ma(a);C(c,function(a){ca(Ba.apply(null,a))})},cb=a,ab=a;q.add("ie-event-behavior",A.attachEvent&&"undefined"===
typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var Ca=function(a,d,c,f){if(q("ie-event-behavior"))return a.attachEvent(c,f),function(){a.detachEvent(c,f)};a.addEventListener(d,f,!1);return function(){a.removeEventListener(d,f,!1)}},jb=Ca(window,"load","onload",function(){t.pageLoaded=1;try{"complete"!=A.readyState&&(A.readyState="complete")}catch(B){}jb()});e=A.getElementsByTagName("script");for(c=0;!la;)/^dojo/.test((k=e[c++])&&k.type)||(la=k);t.injectUrl=function(a,
d,c){c=c.node=A.createElement("script");var f=Ca(c,"load","onreadystatechange",function(a){a=a||window.event;var c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))f(),b(),d&&d()}),b=Ca(c,"error","onerror",function(d){f();b();Q("error",x("scriptError: "+a,[a,d]))});c.type="text/javascript";c.charset="utf-8";c.src=a;la.parentNode.insertBefore(c,la);return c};t.log=a;t.trace=a;if(q("foreign-loader"))fa=a;else{var fa=function(a,d,c){var b=arguments.length,g=["require",
"exports","module"],e=[0,a,d];1==b?e=[0,f(a)?g:[],a]:2==b&&r(a)?e=[a,f(d)?g:[],d]:3==b&&(e=[a,d,c]);t.trace("loader-define",e.slice(0,2));if((b=e[0]&&N(e[0]))&&!L[b.mid])ca(Ba(b,e[1],e[2]));else if(!q("ie-event-behavior")||Aa)pa.push(e);else{b=b||ea;if(!b)for(a in L)if((g=H[a])&&g.node&&"interactive"===g.node.readyState){b=g;break}b?(ma(b),ca(Ba(b,e[1],e[2]))):Q("error",x("ieDefineFailed",e[0]));U()}};fa.amd={vendor:"dojotoolkit.org"};t.def=fa}u(u(t,m.loaderPatch),b.loaderPatch);Ya("error",function(a){try{if(console.error(a),
a instanceof Error)for(var d in a);}catch(Da){}});u(t,{uid:y,cache:P,packs:Z});if(!w.define&&(w.define=fa,w.require=t,!q("foreign-loader"))){C(Ma,function(a){ba(a)});var Ua=ua.deps||b.deps||m.deps,Va=ua.callback||b.callback||m.callback;t.boot=Ua||Va?[Ua||[],Va]:0}})(function(b){return b.dojoConfig||b.djConfig||b.require||{}},{async:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"}]});
require({cache:{"dojo/_base/declare":function(){define(["./kernel","../has","./lang"],function(b,m,h){function k(a,d){throw Error("declare"+(d?" "+d:"")+": "+a);}function e(a,d){for(var c=[],f=[{cls:0,refs:[]}],b={},g=1,e=a.length,l=0,r,n,q,h,v;l<e;++l){(r=a[l])?"[object Function]"!=E.call(r)&&k("mixin #"+l+" is not a callable constructor.",d):k("mixin #"+l+" is unknown. Did you use dojo.require to pull it in?",d);n=r._meta?r._meta.bases:[r];q=0;for(r=n.length-1;0<=r;--r)h=n[r].prototype,h.hasOwnProperty("declaredClass")||
(h.declaredClass="uniqName_"+p++),h=h.declaredClass,b.hasOwnProperty(h)||(b[h]={count:0,refs:[],cls:n[r]},++g),h=b[h],q&&q!==h&&(h.refs.push(q),++q.count),q=h;++q.count;f[0].refs.push(q)}for(;f.length;){q=f.pop();c.push(q.cls);for(--g;v=q.refs,1==v.length;){q=v[0];if(!q||--q.count){q=0;break}c.push(q.cls);--g}if(q)for(l=0,e=v.length;l<e;++l)q=v[l],--q.count||f.push(q)}g&&k("can't build consistent linearization",d);r=a[0];c[0]=r?r._meta&&r===c[c.length-r._meta.bases.length]?r._meta.bases.length:1:
0;return c}function c(a,d,c,f){var b,g,e,l,r,p,q=this._inherited=this._inherited||{};"string"===typeof a&&(b=a,a=d,d=c,c=f);if("function"===typeof a)e=a,a=d,d=c;else try{e=a.callee}catch(O){if(O instanceof TypeError)k("strict mode inherited() requires the caller function to be passed before arguments",this.declaredClass);else throw O;}(b=b||e.nom)||k("can't deduce a name to call inherited()",this.declaredClass);c=f=0;l=this.constructor._meta;f=l.bases;p=q.p;if("constructor"!=b){if(q.c!==e&&(p=0,r=
f[0],l=r._meta,l.hidden[b]!==e)){(g=l.chains)&&"string"==typeof g[b]&&k("calling chained method with inherited: "+b,this.declaredClass);do if(l=r._meta,g=r.prototype,l&&(g[b]===e&&g.hasOwnProperty(b)||l.hidden[b]===e))break;while(r=f[++p]);p=r?p:-1}if(r=f[++p])if(g=r.prototype,r._meta&&g.hasOwnProperty(b))c=g[b];else{e=A[b];do if(g=r.prototype,(c=g[b])&&(r._meta?g.hasOwnProperty(b):c!==e))break;while(r=f[++p])}c=r&&c||A[b]}else{if(q.c!==e&&(p=0,(l=f[0]._meta)&&l.ctor!==e)){for((g=l.chains)&&"manual"===
g.constructor||k("calling chained constructor with inherited",this.declaredClass);(r=f[++p])&&(!(l=r._meta)||l.ctor!==e););p=r?p:-1}for(;(r=f[++p])&&!(c=(l=r._meta)?l.ctor:r););c=r&&c}q.c=c;q.p=p;if(c)return!0===d?c:c.apply(this,d||a)}function n(a,d,c){return"string"===typeof a?"function"===typeof d?this.__inherited(a,d,c,!0):this.__inherited(a,d,!0):"function"===typeof a?this.__inherited(a,d,!0):this.__inherited(a,!0)}function a(a,d,c,f){var b=this.getInherited(a,d,c);if(b)return b.apply(this,f||
c||d||a)}function g(a){for(var d=this.constructor._meta.bases,c=0,f=d.length;c<f;++c)if(d[c]===a)return!0;return this instanceof a}function d(a,d){for(var c in d)"constructor"!=c&&d.hasOwnProperty(c)&&(a[c]=d[c]);if(m("bug-for-in-skips-shadowed"))for(var f=h._extraNames,b=f.length;b;)c=f[--b],"constructor"!=c&&d.hasOwnProperty(c)&&(a[c]=d[c])}function f(a){t.safeMixin(this.prototype,a);return this}function r(a,d){a instanceof Array||"function"===typeof a||(d=a,a=void 0);d=d||{};a=a||[];return t([this].concat(a),
d)}function l(a,d){return function(){var c=arguments,f=c,b=c[0],g,e;e=a.length;var l;if(!(this instanceof c.callee))return y(c);if(d&&(b&&b.preamble||this.preamble))for(l=Array(a.length),l[0]=c,g=0;;){(b=c[0])&&(b=b.preamble)&&(c=b.apply(this,c)||c);b=a[g].prototype;(b=b.hasOwnProperty("preamble")&&b.preamble)&&(c=b.apply(this,c)||c);if(++g==e)break;l[g]=c}for(g=e-1;0<=g;--g)b=a[g],(b=(e=b._meta)?e.ctor:b)&&b.apply(this,l?l[g]:c);(b=this.postscript)&&b.apply(this,f)}}function C(a,d){return function(){var c=
arguments,b=c,f=c[0];if(!(this instanceof c.callee))return y(c);d&&(f&&(f=f.preamble)&&(b=f.apply(this,b)||b),(f=this.preamble)&&f.apply(this,b));a&&a.apply(this,c);(f=this.postscript)&&f.apply(this,c)}}function u(a){return function(){var d=arguments,c=0,b,f;if(!(this instanceof d.callee))return y(d);for(;b=a[c];++c)if(b=(f=b._meta)?f.ctor:b){b.apply(this,d);break}(b=this.postscript)&&b.apply(this,d)}}function x(a,d,c){return function(){var b,f,g=0,e=1;c&&(g=d.length-1,e=-1);for(;b=d[g];g+=e)f=b._meta,
(b=(f?f.hidden:b.prototype)[a])&&b.apply(this,arguments)}}function z(a){q.prototype=a.prototype;a=new q;q.prototype=null;return a}function y(a){var d=a.callee,c=z(d);d.apply(c,a);return c}function t(a,b,p){"string"!=typeof a&&(p=b,b=a,a="");p=p||{};var q,y,v,D,F,I,G,R=1,O=b;"[object Array]"==E.call(b)?(I=e(b,a),v=I[0],R=I.length-v,b=I[R]):(I=[0],b?"[object Function]"==E.call(b)?(v=b._meta,I=I.concat(v?v.bases:b)):k("base class is not a callable constructor.",a):null!==b&&k("unknown base class. Did you use dojo.require to pull it in?",
a));if(b)for(y=R-1;;--y){q=z(b);if(!y)break;v=I[y];(v._meta?d:w)(q,v.prototype);D=m("csp-restrictions")?function(){}:new Function;D.superclass=b;D.prototype=q;b=q.constructor=D}else q={};t.safeMixin(q,p);v=p.constructor;v!==A.constructor&&(v.nom="constructor",q.constructor=v);for(y=R-1;y;--y)(v=I[y]._meta)&&v.chains&&(G=w(G||{},v.chains));q["-chains-"]&&(G=w(G||{},q["-chains-"]));b&&b.prototype&&b.prototype["-chains-"]&&(G=w(G||{},b.prototype["-chains-"]));v=!G||!G.hasOwnProperty("constructor");I[0]=
D=G&&"manual"===G.constructor?u(I):1==I.length?C(p.constructor,v):l(I,v);D._meta={bases:I,hidden:p,chains:G,parents:O,ctor:p.constructor};D.superclass=b&&b.prototype;D.extend=f;D.createSubclass=r;D.prototype=q;q.constructor=D;q.getInherited=n;q.isInstanceOf=g;q.inherited=J;q.__inherited=c;a&&(q.declaredClass=a,h.setObject(a,D));if(G)for(F in G)q[F]&&"string"==typeof G[F]&&"constructor"!=F&&(v=q[F]=x(F,I,"after"===G[F]),v.nom=F);return D}var w=h.mixin,A=Object.prototype,E=A.toString,q,p=0;q=m("csp-restrictions")?
function(){}:new Function;var J=b.config.isDebug?a:c;b.safeMixin=t.safeMixin=function(a,d){var c,b;for(c in d)b=d[c],b===A[c]&&c in A||"constructor"==c||("[object Function]"==E.call(b)&&(b.nom=c),a[c]=b);if(m("bug-for-in-skips-shadowed")&&d)for(var f=h._extraNames,g=f.length;g;)c=f[--g],b=d[c],b===A[c]&&c in A||"constructor"==c||("[object Function]"==E.call(b)&&(b.nom=c),a[c]=b);return a};return b.declare=t})},"dojo/_base/kernel":function(){define(["../global","../has","./config","require","module"],
function(b,m,h,k,e){var c,n={},a={},g={config:h,global:b,dijit:n,dojox:a},n={dojo:["dojo",g],dijit:["dijit",n],dojox:["dojox",a]};e=k.map&&k.map[e.id.match(/[^\/]+/)[0]];for(c in e)n[c]?n[c][0]=e[c]:n[c]=[e[c],{}];for(c in n)e=n[c],e[1]._scopeName=e[0],h.noGlobals||(b[e[0]]=e[1]);g.scopeMap=n;g.baseUrl=g.config.baseUrl=k.baseUrl;g.isAsync=k.async;g.locale=h.locale;b="$Rev:$".match(/[0-9a-f]{7,}/);g.version={major:1,minor:16,patch:2,flag:"",revision:b?b[0]:NaN,toString:function(){var a=g.version;return a.major+
"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};m("csp-restrictions")||Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(g);g.exit=function(){};m("host-webworker");m.add("console-as-object",function(){return Function.prototype.bind&&console&&"object"===typeof console.log});"undefined"!=typeof console||(console={});e="assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" ");
var d;for(b=0;d=e[b++];)console[d]?m("console-as-object")&&(console[d]=Function.prototype.bind.call(console[d],console)):function(){var a=d+"";console[a]="log"in console?function(){var d=Array.prototype.slice.call(arguments);d.unshift(a+":");console.log(d.join(" "))}:function(){};console[a]._fake=!0}();m.add("dojo-debug-messages",!!h.isDebug);g.deprecated=g.experimental=function(){};m("dojo-debug-messages")&&(g.deprecated=function(a,d,c){a="DEPRECATED: "+a;d&&(a+=" "+d);c&&(a+=" -- will be removed in version: "+
c);console.warn(a)},g.experimental=function(a,d){var c="EXPERIMENTAL: "+a+" -- APIs subject to change without notice.";d&&(c+=" "+d);console.warn(c)});if(h.modulePaths){g.deprecated("dojo.modulePaths","use paths configuration");m={};for(c in h.modulePaths)m[c.replace(/\./g,"/")]=h.modulePaths[c];k({paths:m})}g.moduleUrl=function(a,d){g.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var c=null;a&&(c=k.toUrl(a.replace(/\./g,"/")+(d?"/"+d:"")+"/*.*").replace(/\/\*\.\*/,"")+(d?"":"/"));return c};
g._hasResource={};return g})},"dojo/global":function(){define(function(){return"undefined"!==typeof global&&"function"!==typeof global?global:"undefined"!==typeof window?window:"undefined"!==typeof self?self:this})},"dojo/has":function(){define(["./global","require","module"],function(b,m,h){var k=m.has||function(){};k.add("dom-addeventlistener",!!document.addEventListener);k.add("touch","ontouchstart"in document||"onpointerdown"in document&&0<navigator.maxTouchPoints||window.navigator.msMaxTouchPoints);
k.add("touch-events","ontouchstart"in document);k.add("pointer-events","pointerEnabled"in window.navigator?window.navigator.pointerEnabled:"PointerEvent"in window);k.add("MSPointer",window.navigator.msPointerEnabled);k.add("touch-action",k("touch")&&k("pointer-events"));k.add("device-width",screen.availWidth||innerWidth);b=document.createElement("form");k.add("dom-attributes-explicit",0==b.attributes.length);k.add("dom-attributes-specified-flag",0<b.attributes.length&&40>b.attributes.length);k.clearElement=
function(b){b.innerHTML="";return b};k.normalize=function(b,c){var e=b.match(/[\?:]|[^:\?]*/g),a=0,g=function(d){var c=e[a++];if(":"==c)return 0;if("?"==e[a++]){if(!d&&k(c))return g();g(!0);return g(d)}return c||0};return(b=g())&&c(b)};k.load=function(b,c,k){b?c([b],k):k()};return k})},"dojo/_base/config":function(){define(["../global","../has","require"],function(b,m,h){b={};h=h.rawConfig;for(var k in h)b[k]=h[k];!b.locale&&"undefined"!=typeof navigator&&(k=navigator.languages&&navigator.languages.length?
navigator.languages[0]:navigator.language||navigator.userLanguage)&&(b.locale=k.toLowerCase());return b})},"dojo/_base/lang":function(){define(["./kernel","../has","../sniff"],function(b,m){m.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var h=m("bug-for-in-skips-shadowed")?"hasOwnProperty valueOf isPrototypeOf propertyIsEnumerable toLocaleString toString constructor".split(" "):[],k=h.length,e=function(a,c,g){g||(g=a[0]&&b.scopeMap[a[0]]?b.scopeMap[a.shift()][1]:
b.global);try{for(var d=0;d<a.length;d++){var f=a[d];if(!(f in g))if(c)g[f]={};else return;g=g[f]}return g}catch(u){}},c=Object.prototype.toString,n=function(a,c,b){return(b||[]).concat(Array.prototype.slice.call(a,c||0))},a=/\{([^\}]+)\}/g,g={_extraNames:h,_mixin:function(a,c,b){var d,f,g,e={};for(d in c)f=c[d],d in a&&(a[d]===f||d in e&&e[d]===f)||(a[d]=b?b(f):f);if(m("bug-for-in-skips-shadowed")&&c)for(g=0;g<k;++g)d=h[g],f=c[d],d in a&&(a[d]===f||d in e&&e[d]===f)||(a[d]=b?b(f):f);return a},mixin:function(a,
c){a||(a={});for(var d=1,b=arguments.length;d<b;d++)g._mixin(a,arguments[d]);return a},setObject:function(a,c,b){var d=a.split(".");a=d.pop();return(b=e(d,!0,b))&&a?b[a]=c:void 0},getObject:function(a,c,b){return a?e(a.split("."),c,b):b},exists:function(a,c){return void 0!==g.getObject(a,!1,c)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:Array.isArray||function(a){return"[object Array]"==c.call(a)},isFunction:function(a){return"[object Function]"===c.call(a)},isObject:function(a){return void 0!==
a&&(null===a||"object"==typeof a||g.isArray(a)||g.isFunction(a))},isArrayLike:function(a){return!!a&&!g.isString(a)&&!g.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&(g.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!g.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a,c){for(var d=1,b=arguments.length;d<b;d++)g._mixin(a.prototype,arguments[d]);return a},_hitchArgs:function(a,c){var d=g._toArray(arguments,2),f=g.isString(c);return function(){var e=
g._toArray(arguments),l=f?(a||b.global)[c]:c;return l&&l.apply(a||this,d.concat(e))}},hitch:function(a,c){if(2<arguments.length)return g._hitchArgs.apply(b,arguments);c||(c=a,a=null);if(g.isString(c)){a=a||b.global;if(!a[c])throw['lang.hitch: scope["',c,'"] is null (scope\x3d"',a,'")'].join("");return function(){return a[c].apply(a,arguments||[])}}return a?function(){return c.apply(a,arguments||[])}:c},delegate:function(){function a(){}return function(c,d){a.prototype=c;var b=new a;a.prototype=null;
d&&g._mixin(b,d);return b}}(),_toArray:m("ie")?function(){function a(a,c,d){d=d||[];for(c=c||0;c<a.length;c++)d.push(a[c]);return d}return function(c){return(c.item?a:n).apply(this,arguments)}}():n,partial:function(a){return g.hitch.apply(b,[null].concat(g._toArray(arguments)))},clone:function(a){if(!a||"object"!=typeof a||g.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return new RegExp(a);var c,
d,b;if(g.isArray(a))for(c=[],d=0,b=a.length;d<b;++d)d in a&&(c[d]=g.clone(a[d]));else c=a.constructor?new a.constructor:{};return g._mixin(c,a,g.clone)},trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(c,b,e){return c.replace(e||a,g.isFunction(b)?b:function(a,c){return g.getObject(c,!1,b)})}};g.mixin(b,g);return g})},"dojo/sniff":function(){define(["./has"],function(b){var m=navigator,h=m.userAgent,m=m.appVersion,
k=parseFloat(m);b.add("air",0<=h.indexOf("AdobeAIR"));b.add("wp",parseFloat(h.split("Windows Phone")[1])||void 0);b.add("msapp",parseFloat(h.split("MSAppHost/")[1])||void 0);b.add("khtml",0<=m.indexOf("Konqueror")?k:void 0);b.add("edge",parseFloat(h.split("Edge/")[1])||void 0);b.add("opr",parseFloat(h.split("OPR/")[1])||void 0);b.add("webkit",!b("wp")&&!b("edge")&&parseFloat(h.split("WebKit/")[1])||void 0);b.add("chrome",!b("edge")&&!b("opr")&&parseFloat(h.split("Chrome/")[1])||void 0);b.add("android",
!b("wp")&&parseFloat(h.split("Android ")[1])||void 0);b.add("safari",!(0<=m.indexOf("Safari"))||b("wp")||b("chrome")||b("android")||b("edge")||b("opr")?void 0:parseFloat(m.split("Version/")[1]));b.add("mac",0<=m.indexOf("Macintosh"));b.add("quirks","BackCompat"==document.compatMode);if(!b("wp")&&h.match(/(iPhone|iPod|iPad)/)){var e=RegExp.$1.replace(/P/,"p"),c=h.match(/OS ([\d_]+)/)?RegExp.$1:"1",c=parseFloat(c.replace(/_/,".").replace(/_/g,""));b.add(e,c);b.add("ios",c)}b.add("bb",(0<=h.indexOf("BlackBerry")||
0<=h.indexOf("BB10"))&&parseFloat(h.split("Version/")[1])||void 0);b.add("trident",parseFloat(m.split("Trident/")[1])||void 0);b.add("svg","undefined"!==typeof SVGAngle);b("webkit")||(0<=h.indexOf("Opera")&&b.add("opera",9.8<=k?parseFloat(h.split("Version/")[1])||k:k),!(0<=h.indexOf("Gecko"))||b("wp")||b("khtml")||b("trident")||b("edge")||b.add("mozilla",k),b("mozilla")&&b.add("ff",parseFloat(h.split("Firefox/")[1]||h.split("Minefield/")[1])||void 0),document.all&&!b("opera")&&(h=parseFloat(m.split("MSIE ")[1])||
void 0,(m=document.documentMode)&&5!=m&&Math.floor(h)!=m&&(h=m),b.add("ie",h)),b.add("wii","undefined"!=typeof opera&&opera.wiiremote));return b})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(b,m,h){function k(a){return n[a]=new Function("item","index","array",a)}function e(a){var c=!a;return function(d,b,f){var g=0,e=d&&d.length||0,l;e&&"string"==typeof d&&(d=d.split(""));"string"==typeof b&&(b=n[b]||k(b));if(f)for(;g<e;++g){if(l=!b.call(f,d[g],g,d),a^l)return!l}else for(;g<
e;++g)if(l=!b(d[g],g,d),a^l)return!l;return c}}function c(c){var d=1,b=0,e=0;c||(d=b=e=-1);return function(f,k,l,n){if(n&&0<d)return g.lastIndexOf(f,k,l);n=f&&f.length||0;var h=c?n+e:b;l===a?l=c?b:n+e:0>l?(l=n+l,0>l&&(l=b)):l=l>=n?n+e:l;for(n&&"string"==typeof f&&(f=f.split(""));l!=h;l+=d)if(f[l]==k)return l;return-1}}var n={},a,g={every:e(!1),some:e(!0),indexOf:c(!0),lastIndexOf:c(!1),forEach:function(a,c,b){var d=0,f=a&&a.length||0;f&&"string"==typeof a&&(a=a.split(""));"string"==typeof c&&(c=n[c]||
k(c));if(b)for(;d<f;++d)c.call(b,a[d],d,a);else for(;d<f;++d)c(a[d],d,a)},map:function(a,c,b,g){var d=0,f=a&&a.length||0;g=new (g||Array)(f);f&&"string"==typeof a&&(a=a.split(""));"string"==typeof c&&(c=n[c]||k(c));if(b)for(;d<f;++d)g[d]=c.call(b,a[d],d,a);else for(;d<f;++d)g[d]=c(a[d],d,a);return g},filter:function(a,c,b){var d=0,g=a&&a.length||0,f=[],e;g&&"string"==typeof a&&(a=a.split(""));"string"==typeof c&&(c=n[c]||k(c));if(b)for(;d<g;++d)e=a[d],c.call(b,e,d,a)&&f.push(e);else for(;d<g;++d)e=
a[d],c(e,d,a)&&f.push(e);return f},clearCache:function(){n={}}};h.mixin(b,g);return g})},"dojo/date":function(){define(["./has","./_base/lang"],function(b,m){var h={getDaysInMonth:function(b){var e=b.getMonth();return 1==e&&h.isLeapYear(b)?29:[31,28,31,30,31,30,31,31,30,31,30,31][e]},isLeapYear:function(b){b=b.getFullYear();return!(b%400)||!(b%4)&&!!(b%100)},getTimezoneName:function(b){var e=b.toString(),c="",k=e.indexOf("(");if(-1<k)c=e.substring(++k,e.indexOf(")"));else if(k=/([A-Z\/]+) \d{4}$/,
e=e.match(k))c=e[1];else if(e=b.toLocaleString(),k=/ ([A-Z\/]+)$/,e=e.match(k))c=e[1];return"AM"==c||"PM"==c?"":c},compare:function(b,e,c){b=new Date(+b);e=new Date(+(e||new Date));"date"==c?(b.setHours(0,0,0,0),e.setHours(0,0,0,0)):"time"==c&&(b.setFullYear(0,0,0),e.setFullYear(0,0,0));return b>e?1:b<e?-1:0},add:function(b,e,c){var k=new Date(+b),a=!1,g="Date";switch(e){case "day":break;case "weekday":var d;(e=c%5)?d=parseInt(c/5):(e=0<c?5:-5,d=0<c?(c-5)/5:(c+5)/5);var f=b.getDay(),h=0;6==f&&0<c?
h=1:0==f&&0>c&&(h=-1);f+=e;if(0==f||6==f)h=0<c?2:-2;c=7*d+e+h;break;case "year":g="FullYear";a=!0;break;case "week":c*=7;break;case "quarter":c*=3;case "month":a=!0;g="Month";break;default:g="UTC"+e.charAt(0).toUpperCase()+e.substring(1)+"s"}if(g)k["set"+g](k["get"+g]()+c);a&&k.getDate()<b.getDate()&&k.setDate(0);return k},difference:function(b,e,c){e=e||new Date;c=c||"day";var k=e.getFullYear()-b.getFullYear(),a=1;switch(c){case "quarter":b=b.getMonth();e=e.getMonth();a=Math.floor(e/3)+1+4*k-(Math.floor(b/
3)+1);break;case "weekday":k=Math.round(h.difference(b,e,"day"));c=parseInt(h.difference(b,e,"week"));if(0==k%7)k=5*c;else{var a=0,g=b.getDay(),d=e.getDay();c=parseInt(k/7);e=k%7;b=new Date(b);b.setDate(b.getDate()+7*c);b=b.getDay();if(0<k)switch(!0){case 6==g:a=-1;break;case 0==g:a=0;break;case 6==d:a=-1;break;case 0==d:a=-2;break;case 5<b+e:a=-2}else if(0>k)switch(!0){case 6==g:a=0;break;case 0==g:a=1;break;case 6==d:a=2;break;case 0==d:a=1;break;case 0>b+e:a=2}k=k+a-2*c}a=k;break;case "year":a=
k;break;case "month":a=e.getMonth()-b.getMonth()+12*k;break;case "week":a=parseInt(h.difference(b,e,"day")/7);break;case "day":a/=24;case "hour":a/=60;case "minute":a/=60;case "second":a/=1E3;case "millisecond":a*=e.getTime()-b.getTime()}return Math.round(a)}};m.mixin(m.getObject("dojo.date",!0),h);return h})},"dojo/date/locale":function(){define("../_base/lang ../_base/array ../date ../cldr/supplemental ../i18n ../regexp ../string ../i18n!../cldr/nls/gregorian module".split(" "),function(b,m,h,k,
e,c,n,a,g){function d(a,c,b,d){return d.replace(/([a-z])\1*/ig,function(g){var f,e,p=g.charAt(0);g=g.length;var h=["abbr","wide","narrow"];switch(p){case "G":f=c[4>g?"eraAbbr":"eraNames"][0>a.getFullYear()?0:1];break;case "y":f=a.getFullYear();switch(g){case 1:break;case 2:if(!b.fullYear){f=String(f);f=f.substr(f.length-2);break}default:e=!0}break;case "Q":case "q":f=Math.ceil((a.getMonth()+1)/3);e=!0;break;case "M":case "L":f=a.getMonth();3>g?(f+=1,e=!0):(p=["months","L"==p?"standAlone":"format",
h[g-3]].join("-"),f=c[p][f]);break;case "w":f=l._getWeekOfYear(a,0);e=!0;break;case "d":f=a.getDate();e=!0;break;case "D":f=l._getDayOfYear(a);e=!0;break;case "e":case "c":if(f=a.getDay(),2>g){f=(f-k.getFirstDayOfWeek(b.locale)+8)%7;break}case "E":f=a.getDay();3>g?(f+=1,e=!0):(p=["days","c"==p?"standAlone":"format",h[g-3]].join("-"),f=c[p][f]);break;case "a":p=12>a.getHours()?"am":"pm";f=b[p]||c["dayPeriods-format-wide-"+p];break;case "h":case "H":case "K":case "k":e=a.getHours();switch(p){case "h":f=
e%12||12;break;case "H":f=e;break;case "K":f=e%12;break;case "k":f=e||24}e=!0;break;case "m":f=a.getMinutes();e=!0;break;case "s":f=a.getSeconds();e=!0;break;case "S":f=Math.round(a.getMilliseconds()*Math.pow(10,g-3));e=!0;break;case "v":case "z":if(f=l._getZone(a,!0,b))break;g=4;case "Z":p=l._getZone(a,!1,b);p=[0>=p?"+":"-",n.pad(Math.floor(Math.abs(p)/60),2),n.pad(Math.abs(p)%60,2)];4==g&&(p.splice(0,0,"GMT"),p.splice(3,0,":"));f=p.join("");break;default:throw Error("dojo.date.locale.format: invalid pattern char: "+
d);}e&&(f=n.pad(f,g));return f})}function f(a,c,b,d){var f=function(a){return a};c=c||f;b=b||f;d=d||f;var g=a.match(/(''|[^'])+/g),e="'"==a.charAt(0);m.forEach(g,function(a,d){a?(g[d]=(e?b:c)(a.replace(/''/g,"'")),e=!e):g[d]=""});return d(g.join(""))}function r(a,b,d,f){f=c.escapeString(f);d.strict||(f=f.replace(" a"," ?a"));return f.replace(/([a-z])\1*/ig,function(c){var f;f=c.charAt(0);var g=c.length,e="",l="";d.strict?(1<g&&(e="0{"+(g-1)+"}"),2<g&&(l="0{"+(g-2)+"}")):(e="0?",l="0{0,2}");switch(f){case "y":f=
"\\d{2,4}";break;case "M":case "L":2<g?(f=b["months-"+("L"==f?"standAlone":"format")+"-"+C[g-3]].slice(0).join("|"),d.strict||(f=f.replace(/\./g,""),f="(?:"+f+")\\.?")):f="1[0-2]|"+e+"[1-9]";break;case "D":f="[12][0-9][0-9]|3[0-5][0-9]|36[0-6]|"+e+"[1-9][0-9]|"+l+"[1-9]";break;case "d":f="3[01]|[12]\\d|"+e+"[1-9]";break;case "w":f="[1-4][0-9]|5[0-3]|"+e+"[1-9]";break;case "E":case "e":case "c":f=".+?";break;case "h":f="1[0-2]|"+e+"[1-9]";break;case "k":f="1[01]|"+e+"\\d";break;case "H":f="1\\d|2[0-3]|"+
e+"\\d";break;case "K":f="1\\d|2[0-4]|"+e+"[1-9]";break;case "m":case "s":f="[0-5]\\d";break;case "S":f="\\d{"+g+"}";break;case "a":g=d.am||b["dayPeriods-format-wide-am"];e=d.pm||b["dayPeriods-format-wide-pm"];f=g+"|"+e;d.strict||(g!=g.toLowerCase()&&(f+="|"+g.toLowerCase()),e!=e.toLowerCase()&&(f+="|"+e.toLowerCase()),-1!=f.indexOf(".")&&(f+="|"+f.replace(/\./g,"")));f=f.replace(/\./g,"\\.");break;default:f=".*"}a&&a.push(c);return"("+f+")"}).replace(/[\xa0 ]/g,"[\\s\\xa0]")}var l={};b.setObject(g.id.replace(/\//g,
"."),l);l._getZone=function(a,c,b){return c?h.getTimezoneName(a):a.getTimezoneOffset()};l.format=function(a,c){c=c||{};var g=e.normalizeLocale(c.locale),k=c.formatLength||"short",g=l._getGregorianBundle(g),h=[],n=b.hitch(this,d,a,g,c);if("year"==c.selector)return f(g["dateFormatItem-yyyy"]||"yyyy",n);var q;"date"!=c.selector&&(q=c.timePattern||g["timeFormat-"+k])&&h.push(f(q,n));"time"!=c.selector&&(q=c.datePattern||g["dateFormat-"+k])&&h.push(f(q,n));return 1==h.length?h[0]:g["dateTimeFormat-"+k].replace(/\'/g,
"").replace(/\{(\d+)\}/g,function(a,c){return h[c]})};l.regexp=function(a){return l._parseInfo(a).regexp};l._parseInfo=function(a){a=a||{};var c=e.normalizeLocale(a.locale),c=l._getGregorianBundle(c),d=a.formatLength||"short",g=a.datePattern||c["dateFormat-"+d],k=a.timePattern||c["timeFormat-"+d],d="date"==a.selector?g:"time"==a.selector?k:c["dateTimeFormat-"+d].replace(/\{(\d+)\}/g,function(a,c){return[k,g][c]}),h=[];return{regexp:f(d,b.hitch(this,r,h,c,a)),tokens:h,bundle:c}};l.parse=function(a,
c){var b=/[\u200E\u200F\u202A\u202E]/g,d=l._parseInfo(c),f=d.tokens,g=d.bundle,b=(new RegExp("^"+d.regexp.replace(b,"")+"$",d.strict?"":"i")).exec(a&&a.replace(b,""));if(!b)return null;var e=["abbr","wide","narrow"],p=[1970,0,1,0,0,0,0],k="",b=m.every(b,function(a,b){if(!b)return!0;var d=f[b-1],l=d.length,d=d.charAt(0);switch(d){case "y":if(2!=l&&c.strict)p[0]=a;else if(100>a)a=Number(a),d=""+(new Date).getFullYear(),l=100*d.substring(0,2),d=Math.min(Number(d.substring(2,4))+20,99),p[0]=a<d?l+a:l-
100+a;else{if(c.strict)return!1;p[0]=a}break;case "M":case "L":if(2<l){if(l=g["months-"+("L"==d?"standAlone":"format")+"-"+e[l-3]].concat(),c.strict||(a=a.replace(".","").toLowerCase(),l=m.map(l,function(a){return a.replace(".","").toLowerCase()})),a=m.indexOf(l,a),-1==a)return!1}else a--;p[1]=a;break;case "E":case "e":case "c":l=g["days-"+("c"==d?"standAlone":"format")+"-"+e[l-3]].concat();c.strict||(a=a.toLowerCase(),l=m.map(l,function(a){return a.toLowerCase()}));a=m.indexOf(l,a);if(-1==a)return!1;
break;case "D":p[1]=0;case "d":p[2]=a;break;case "a":l=c.am||g["dayPeriods-format-wide-am"];d=c.pm||g["dayPeriods-format-wide-pm"];if(!c.strict){var h=/\./g;a=a.replace(h,"").toLowerCase();l=l.replace(h,"").toLowerCase();d=d.replace(h,"").toLowerCase()}if(c.strict&&a!=l&&a!=d)return!1;k=a==d?"p":a==l?"a":"";break;case "K":24==a&&(a=0);case "h":case "H":case "k":if(23<a)return!1;p[3]=a;break;case "m":p[4]=a;break;case "s":p[5]=a;break;case "S":p[6]=a}return!0}),d=+p[3];"p"===k&&12>d?p[3]=d+12:"a"===
k&&12==d&&(p[3]=0);d=new Date(p[0],p[1],p[2],p[3],p[4],p[5],p[6]);c.strict&&d.setFullYear(p[0]);var n=f.join(""),r=-1!=n.indexOf("d"),n=-1!=n.indexOf("M");if(!b||n&&d.getMonth()>p[1]||r&&d.getDate()>p[2])return null;if(n&&d.getMonth()<p[1]||r&&d.getDate()<p[2])d=h.add(d,"hour",1);return d};var C=["abbr","wide","narrow"],u=[],x={};l.addCustomFormats=function(a,c){u.push({pkg:a,name:c});x={}};l._getGregorianBundle=function(a){if(x[a])return x[a];var c={};m.forEach(u,function(d){d=e.getLocalization(d.pkg,
d.name,a);c=b.mixin(c,d)},this);return x[a]=c};l.addCustomFormats(g.id.replace(/\/date\/locale$/,".cldr"),"gregorian");l.getNames=function(a,c,b,d){var f;d=l._getGregorianBundle(d);a=[a,b,c];"standAlone"==b&&(b=a.join("-"),f=d[b],1==f[0]&&(f=void 0));a[1]="format";return(f||d[a.join("-")]).concat()};l.isWeekend=function(a,c){var b=k.getWeekend(c),d=(a||new Date).getDay();b.end<b.start&&(b.end+=7,d<b.start&&(d+=7));return d>=b.start&&d<=b.end};l._getDayOfYear=function(a){return h.difference(new Date(a.getFullYear(),
0,1,a.getHours()),a)+1};l._getWeekOfYear=function(a,c){1==arguments.length&&(c=0);var b=(new Date(a.getFullYear(),0,1)).getDay(),d=(b-c+7)%7,d=Math.floor((l._getDayOfYear(a)+d-1)/7);b==c&&d++;return d};return l})},"dojo/cldr/supplemental":function(){define(["../_base/lang","../i18n"],function(b,m){var h={};b.setObject("dojo.cldr.supplemental",h);h.getFirstDayOfWeek=function(b){b={bd:5,mv:5,ae:6,af:6,bh:6,dj:6,dz:6,eg:6,iq:6,ir:6,jo:6,kw:6,ly:6,ma:6,om:6,qa:6,sa:6,sd:6,sy:6,ye:6,ag:0,ar:0,as:0,au:0,
br:0,bs:0,bt:0,bw:0,by:0,bz:0,ca:0,cn:0,co:0,dm:0,"do":0,et:0,gt:0,gu:0,hk:0,hn:0,id:0,ie:0,il:0,"in":0,jm:0,jp:0,ke:0,kh:0,kr:0,la:0,mh:0,mm:0,mo:0,mt:0,mx:0,mz:0,ni:0,np:0,nz:0,pa:0,pe:0,ph:0,pk:0,pr:0,py:0,sg:0,sv:0,th:0,tn:0,tt:0,tw:0,um:0,us:0,ve:0,vi:0,ws:0,za:0,zw:0}[h._region(b)];return void 0===b?1:b};h._region=function(b){b=m.normalizeLocale(b);b=b.split("-");var e=b[1];e?4==e.length&&(e=b[2]):e={aa:"et",ab:"ge",af:"za",ak:"gh",am:"et",ar:"eg",as:"in",av:"ru",ay:"bo",az:"az",ba:"ru",be:"by",
bg:"bg",bi:"vu",bm:"ml",bn:"bd",bo:"cn",br:"fr",bs:"ba",ca:"es",ce:"ru",ch:"gu",co:"fr",cr:"ca",cs:"cz",cv:"ru",cy:"gb",da:"dk",de:"de",dv:"mv",dz:"bt",ee:"gh",el:"gr",en:"us",es:"es",et:"ee",eu:"es",fa:"ir",ff:"sn",fi:"fi",fj:"fj",fo:"fo",fr:"fr",fy:"nl",ga:"ie",gd:"gb",gl:"es",gn:"py",gu:"in",gv:"gb",ha:"ng",he:"il",hi:"in",ho:"pg",hr:"hr",ht:"ht",hu:"hu",hy:"am",ia:"fr",id:"id",ig:"ng",ii:"cn",ik:"us","in":"id",is:"is",it:"it",iu:"ca",iw:"il",ja:"jp",ji:"ua",jv:"id",jw:"id",ka:"ge",kg:"cd",ki:"ke",
kj:"na",kk:"kz",kl:"gl",km:"kh",kn:"in",ko:"kr",ks:"in",ku:"tr",kv:"ru",kw:"gb",ky:"kg",la:"va",lb:"lu",lg:"ug",li:"nl",ln:"cd",lo:"la",lt:"lt",lu:"cd",lv:"lv",mg:"mg",mh:"mh",mi:"nz",mk:"mk",ml:"in",mn:"mn",mo:"ro",mr:"in",ms:"my",mt:"mt",my:"mm",na:"nr",nb:"no",nd:"zw",ne:"np",ng:"na",nl:"nl",nn:"no",no:"no",nr:"za",nv:"us",ny:"mw",oc:"fr",om:"et",or:"in",os:"ge",pa:"in",pl:"pl",ps:"af",pt:"br",qu:"pe",rm:"ch",rn:"bi",ro:"ro",ru:"ru",rw:"rw",sa:"in",sd:"in",se:"no",sg:"cf",si:"lk",sk:"sk",sl:"si",
sm:"ws",sn:"zw",so:"so",sq:"al",sr:"rs",ss:"za",st:"za",su:"id",sv:"se",sw:"tz",ta:"in",te:"in",tg:"tj",th:"th",ti:"et",tk:"tm",tl:"ph",tn:"za",to:"to",tr:"tr",ts:"za",tt:"ru",ty:"pf",ug:"cn",uk:"ua",ur:"pk",uz:"uz",ve:"za",vi:"vn",wa:"be",wo:"sn",xh:"za",yi:"il",yo:"ng",za:"cn",zh:"cn",zu:"za",ace:"id",ady:"ru",agq:"cm",alt:"ru",amo:"ng",asa:"tz",ast:"es",awa:"in",bal:"pk",ban:"id",bas:"cm",bax:"cm",bbc:"id",bem:"zm",bez:"tz",bfq:"in",bft:"pk",bfy:"in",bhb:"in",bho:"in",bik:"ph",bin:"ng",bjj:"in",
bku:"ph",bqv:"ci",bra:"in",brx:"in",bss:"cm",btv:"pk",bua:"ru",buc:"yt",bug:"id",bya:"id",byn:"er",cch:"ng",ccp:"in",ceb:"ph",cgg:"ug",chk:"fm",chm:"ru",chp:"ca",chr:"us",cja:"kh",cjm:"vn",ckb:"iq",crk:"ca",csb:"pl",dar:"ru",dav:"ke",den:"ca",dgr:"ca",dje:"ne",doi:"in",dsb:"de",dua:"cm",dyo:"sn",dyu:"bf",ebu:"ke",efi:"ng",ewo:"cm",fan:"gq",fil:"ph",fon:"bj",fur:"it",gaa:"gh",gag:"md",gbm:"in",gcr:"gf",gez:"et",gil:"ki",gon:"in",gor:"id",grt:"in",gsw:"ch",guz:"ke",gwi:"ca",haw:"us",hil:"ph",hne:"in",
hnn:"ph",hoc:"in",hoj:"in",ibb:"ng",ilo:"ph",inh:"ru",jgo:"cm",jmc:"tz",kaa:"uz",kab:"dz",kaj:"ng",kam:"ke",kbd:"ru",kcg:"ng",kde:"tz",kdt:"th",kea:"cv",ken:"cm",kfo:"ci",kfr:"in",kha:"in",khb:"cn",khq:"ml",kht:"in",kkj:"cm",kln:"ke",kmb:"ao",koi:"ru",kok:"in",kos:"fm",kpe:"lr",krc:"ru",kri:"sl",krl:"ru",kru:"in",ksb:"tz",ksf:"cm",ksh:"de",kum:"ru",lag:"tz",lah:"pk",lbe:"ru",lcp:"cn",lep:"in",lez:"ru",lif:"np",lis:"cn",lki:"ir",lmn:"in",lol:"cd",lua:"cd",luo:"ke",luy:"ke",lwl:"th",mad:"id",mag:"in",
mai:"in",mak:"id",man:"gn",mas:"ke",mdf:"ru",mdh:"ph",mdr:"id",men:"sl",mer:"ke",mfe:"mu",mgh:"mz",mgo:"cm",min:"id",mni:"in",mnk:"gm",mnw:"mm",mos:"bf",mua:"cm",mwr:"in",myv:"ru",nap:"it",naq:"na",nds:"de","new":"np",niu:"nu",nmg:"cm",nnh:"cm",nod:"th",nso:"za",nus:"sd",nym:"tz",nyn:"ug",pag:"ph",pam:"ph",pap:"bq",pau:"pw",pon:"fm",prd:"ir",raj:"in",rcf:"re",rej:"id",rjs:"np",rkt:"in",rof:"tz",rwk:"tz",saf:"gh",sah:"ru",saq:"ke",sas:"id",sat:"in",saz:"in",sbp:"tz",scn:"it",sco:"gb",sdh:"ir",seh:"mz",
ses:"ml",shi:"ma",shn:"mm",sid:"et",sma:"se",smj:"se",smn:"fi",sms:"fi",snk:"ml",srn:"sr",srr:"sn",ssy:"er",suk:"tz",sus:"gn",swb:"yt",swc:"cd",syl:"bd",syr:"sy",tbw:"ph",tcy:"in",tdd:"cn",tem:"sl",teo:"ug",tet:"tl",tig:"er",tiv:"ng",tkl:"tk",tmh:"ne",tpi:"pg",trv:"tw",tsg:"ph",tts:"th",tum:"mw",tvl:"tv",twq:"ne",tyv:"ru",tzm:"ma",udm:"ru",uli:"fm",umb:"ao",unr:"in",unx:"in",vai:"lr",vun:"tz",wae:"ch",wal:"et",war:"ph",xog:"ug",xsr:"np",yao:"mz",yap:"fm",yav:"cm",zza:"tr"}[b[0]];return e};h.getWeekend=
function(b){var e=h._region(b);b={"in":0,af:4,dz:4,ir:4,om:4,sa:4,ye:4,ae:5,bh:5,eg:5,il:5,iq:5,jo:5,kw:5,ly:5,ma:5,qa:5,sd:5,sy:5,tn:5}[e];e={af:5,dz:5,ir:5,om:5,sa:5,ye:5,ae:6,bh:5,eg:6,il:6,iq:6,jo:6,kw:6,ly:6,ma:6,qa:6,sd:6,sy:6,tn:6}[e];void 0===b&&(b=6);void 0===e&&(e=0);return{start:b,end:e}};return h})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(b,m,h,k,e,c,n,a,g){h.add("dojo-preload-i18n-Api",
1);var d=b.i18n={},f=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,r=function(a,c,b,d){var f=[b+d];c=c.split("-");for(var g="",e=0;e<c.length;e++)if(g+=(g?"-":"")+c[e],!a||a[g])f.push(b+g+"/"+d),f.specificity=g;return f},l={},C=function(a,c,d){d=d?d.toLowerCase():b.locale;a=a.replace(/\./g,"/");c=c.replace(/\./g,"/");return/root/i.test(d)?a+"/nls/"+c:a+"/nls/"+d+"/"+c},u=b.getL10nName=function(a,c,b){return a=g.id+"!"+C(a,c,b)},x=function(a,b,d,f,g,e){a([b],function(p){var h=c.clone(p.root||p.ROOT),k=
r(!p._v1x&&p,g,d,f);a(k,function(){for(var a=1;a<k.length;a++)h=c.mixin(c.clone(h),arguments[a]);l[b+"/"+g]=h;h.$locale=k.specificity;e()})})},z=function(a){var b=e.extraLocale||[],b=c.isArray(b)?b:[b];b.push(a);return b},y=function(d,g,e){var p=f.exec(d),n=p[1]+"/",r=p[5]||p[4],v=n+r,u=(p=p[5]&&p[4])||b.locale||"",m=v+"/"+u,p=p?[u]:z(u),t=p.length,J=function(){--t||e(c.delegate(l[m]))},u=d.split("*"),y="preload"==u[1];if(h("dojo-preload-i18n-Api")){if(y&&(l[d]||(l[d]=1,E(u[2],a.parse(u[3]),1,g)),
e(1)),(u=y)||(w&&A.push([d,g,e]),u=w&&!l[m]),u)return}else if(y){e(1);return}k.forEach(p,function(a){var c=v+"/"+a;h("dojo-preload-i18n-Api")&&q(c);l[c]?J():x(g,v,n,r,a,J)})};h("dojo-preload-i18n-Api");var t=d.normalizeLocale=function(a){a=a?a.toLowerCase():b.locale;return"root"==a?"ROOT":a},w=0,A=[],E=d._preloadLocalizations=function(a,d,f,g){function e(a,c){g.isXdUrl(m.toUrl(a+".js"))||f?g([a],c):F([a],c,g)}function p(a,c){for(var b=a.split("-");b.length;){if(c(b.join("-")))return;b.pop()}c("ROOT")}
function h(){for(--w;!w&&A.length;)y.apply(null,A.shift())}function n(b){b=t(b);p(b,function(f){if(0<=k.indexOf(d,f)){var n=a.replace(/\./g,"/")+"_"+f;w++;e(n,function(a){for(var d in a){var e=a[d],k=d.match(/(.+)\/([^\/]+)$/),n;if(k&&(n=k[2],k=k[1]+"/",e._localized)){var q;if("ROOT"===f){var r=q=e._localized;delete e._localized;r.root=e;l[m.toAbsMid(d)]=r}else q=e._localized,l[m.toAbsMid(k+n+"/"+f)]=e;f!==b&&function(a,d,f,e){var k=[],n=[];p(b,function(c){e[c]&&(k.push(m.toAbsMid(a+c+"/"+d)),n.push(m.toAbsMid(a+
d+"/"+c)))});k.length?(w++,g(k,function(){for(var g=k.length-1;0<=g;g--)f=c.mixin(c.clone(f),arguments[g]),l[n[g]]=f;l[m.toAbsMid(a+d+"/"+b)]=c.clone(f);h()})):l[m.toAbsMid(a+d+"/"+b)]=f}(k,n,e,q)}}h()});return!0}return!1})}g=g||m;n();k.forEach(b.config.extraLocale,n)},q=function(){},p={},J={},v,F=function(a,c,b){var d=[];k.forEach(a,function(a){function c(c){v||(v=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"));
c=v(c,q,a,p);c===p?d.push(l[f]=p.result):(c instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+f,c),c={}),d.push(l[f]=/nls\/[^\/]+\/[^\/]+$/.test(f)?c:{root:c,_v1x:1}))}var f=b.toUrl(a+".js");if(l[f])d.push(l[f]);else{var g=b.syncLoadNls(a);g||(g=q(a.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(g)d.push(g);else if(n)n.get({url:f,sync:!0,load:c,error:function(){d.push(l[f]={})}});else try{b.getText(f,!0,c)}catch(R){d.push(l[f]={})}}});c&&c.apply(null,d)},q=function(a){for(var c,
d=a.split("/"),f=b.global[d[0]],g=1;f&&g<d.length-1;f=f[d[g++]]);f&&((c=f[d[g]])||(c=f[d[g].replace(/-/g,"_")]),c&&(l[a]=c));return c};d.getLocalization=function(a,c,b){var d,f=C(a,c,b);if(J[f])return J[f];y(f,m.isXdUrl(m.toUrl(f+".js"))?m:function(a,c){F(a,c,m)},function(a){d=J[f]=a});return d};return c.mixin(d,{dynamic:!0,normalize:function(a,c){return/^\./.test(a)?c(a):a},load:y,cache:l,getL10nName:u})})},"dojo/_base/xhr":function(){define("./kernel ./sniff require ../io-query ../dom ../dom-form ./Deferred ./config ./json ./lang ./array ../on ../aspect ../request/watch ../request/xhr ../request/util".split(" "),
function(b,m,h,k,e,c,n,a,g,d,f,r,l,C,u,x){b._xhrObj=u._create;var z=b.config;b.objectToQuery=k.objectToQuery;b.queryToObject=k.queryToObject;b.fieldToObject=c.fieldToObject;b.formToObject=c.toObject;b.formToQuery=c.toQuery;b.formToJson=c.toJson;b._blockAsync=!1;var y=b._contentHandlers=b.contentHandlers={text:function(a){return a.responseText},json:function(a){return g.fromJson(a.responseText||null)},"json-comment-filtered":function(c){a.useCommentedJson||console.warn("Consider using the standard mimetype:application/json. json-commenting can introduce security issues. To decrease the chances of hijacking, use the standard the 'json' handler and prefix your json with: {}\x26\x26\nUse djConfig.useCommentedJson\x3dtrue to turn off this message.");
c=c.responseText;var b=c.indexOf("/*"),d=c.lastIndexOf("*/");if(-1==b||-1==d)throw Error("JSON was not comment filtered");return g.fromJson(c.substring(b+2,d))},javascript:function(a){return b.eval(a.responseText)},xml:function(a){var c=a.responseXML;c&&m("dom-qsa2.1")&&!c.querySelectorAll&&m("dom-parser")&&(c=(new DOMParser).parseFromString(a.responseText,"application/xml"));if(m("ie")&&(!c||!c.documentElement)){var b=function(a){return"MSXML"+a+".DOMDocument"},b=["Microsoft.XMLDOM",b(6),b(4),b(3),
b(2)];f.some(b,function(b){try{var d=new ActiveXObject(b);d.async=!1;d.loadXML(a.responseText);c=d}catch(D){return!1}return!0})}return c},"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?y["json-comment-filtered"](a):y.json(a)}};b._ioSetArgs=function(a,f,g,l){var p={args:a,url:a.url},h=null;if(a.form){var h=e.byId(a.form),r=h.getAttributeNode("action");p.url=p.url||(r?r.value:b.doc?b.doc.URL:null);h=c.toObject(h)}r={};h&&d.mixin(r,h);a.content&&d.mixin(r,
a.content);a.preventCache&&(r["dojo.preventCache"]=(new Date).valueOf());p.query=k.objectToQuery(r);p.handleAs=a.handleAs||"text";var q=new n(function(a){a.canceled=!0;f&&f(a);var c=a.ioArgs.error;c||(c=Error("request cancelled"),c.dojoType="cancel",a.ioArgs.error=c);return c});q.addCallback(g);var u=a.load;u&&d.isFunction(u)&&q.addCallback(function(c){return u.call(a,c,p)});var x=a.error;x&&d.isFunction(x)&&q.addErrback(function(c){return x.call(a,c,p)});var v=a.handle;v&&d.isFunction(v)&&q.addBoth(function(c){return v.call(a,
c,p)});q.addErrback(function(a){return l(a,q)});z.ioPublish&&b.publish&&!1!==p.args.ioPublish&&(q.addCallbacks(function(a){b.publish("/dojo/io/load",[q,a]);return a},function(a){b.publish("/dojo/io/error",[q,a]);return a}),q.addBoth(function(a){b.publish("/dojo/io/done",[q,a]);return a}));q.ioArgs=p;return q};var t=function(a){a=y[a.ioArgs.handleAs](a.ioArgs.xhr);return void 0===a?null:a},w=function(a,c){c.ioArgs.args.failOk||console.error(a);return a},A=function(a){0>=E&&(E=0,z.ioPublish&&b.publish&&
(!a||a&&!1!==a.ioArgs.args.ioPublish)&&b.publish("/dojo/io/stop"))},E=0;l.after(C,"_onAction",function(){--E});l.after(C,"_onInFlight",A);b._ioCancelAll=C.cancelAll;b._ioNotifyStart=function(a){z.ioPublish&&b.publish&&!1!==a.ioArgs.args.ioPublish&&(E||b.publish("/dojo/io/start"),E+=1,b.publish("/dojo/io/send",[a]))};b._ioWatch=function(a,c,b,f){a.ioArgs.options=a.ioArgs.args;d.mixin(a,{response:a.ioArgs,isValid:function(b){return c(a)},isReady:function(c){return b(a)},handleResponse:function(c){return f(a)}});
C(a);A(a)};b._ioAddQueryToUrl=function(a){a.query.length&&(a.url+=(-1==a.url.indexOf("?")?"?":"\x26")+a.query,a.query=null)};b.xhr=function(a,c,d){var f,g=b._ioSetArgs(c,function(a){f&&f.cancel()},t,w),e=g.ioArgs;"postData"in c?e.query=c.postData:"putData"in c?e.query=c.putData:"rawBody"in c?e.query=c.rawBody:(2<arguments.length&&!d||-1==="POST|PUT".indexOf(a.toUpperCase()))&&b._ioAddQueryToUrl(e);var l={method:a,handleAs:"text",timeout:c.timeout,withCredentials:c.withCredentials,ioArgs:e};"undefined"!==
typeof c.headers&&(l.headers=c.headers);"undefined"!==typeof c.contentType&&(l.headers||(l.headers={}),l.headers["Content-Type"]=c.contentType);"undefined"!==typeof e.query&&(l.data=e.query);"undefined"!==typeof c.sync&&(l.sync=c.sync);b._ioNotifyStart(g);try{f=u(e.url,l,!0)}catch(S){return g.cancel(),g}g.ioArgs.xhr=f.response.xhr;f.then(function(){g.resolve(g)}).otherwise(function(a){e.error=a;a.response&&(a.status=a.response.status,a.responseText=a.response.text,a.xhr=a.response.xhr);g.reject(a)});
return g};b.xhrGet=function(a){return b.xhr("GET",a)};b.rawXhrPost=b.xhrPost=function(a){return b.xhr("POST",a,!0)};b.rawXhrPut=b.xhrPut=function(a){return b.xhr("PUT",a,!0)};b.xhrDelete=function(a){return b.xhr("DELETE",a)};b._isDocumentOk=function(a){return x.checkStatus(a.status)};b._getText=function(a){var c;b.xhrGet({url:a,sync:!0,load:function(a){c=a}});return c};d.mixin(b.xhr,{_xhrObj:b._xhrObj,fieldToObject:c.fieldToObject,formToObject:c.toObject,objectToQuery:k.objectToQuery,formToQuery:c.toQuery,
formToJson:c.toJson,queryToObject:k.queryToObject,contentHandlers:y,_ioSetArgs:b._ioSetArgs,_ioCancelAll:b._ioCancelAll,_ioNotifyStart:b._ioNotifyStart,_ioWatch:b._ioWatch,_ioAddQueryToUrl:b._ioAddQueryToUrl,_isDocumentOk:b._isDocumentOk,_getText:b._getText,get:b.xhrGet,post:b.xhrPost,put:b.xhrPut,del:b.xhrDelete});return b.xhr})},"dojo/_base/sniff":function(){define(["./kernel","./lang","../sniff"],function(b,m,h){b._name="browser";m.mixin(b,{isBrowser:!0,isFF:h("ff"),isIE:h("ie"),isKhtml:h("khtml"),
isWebKit:h("webkit"),isMozilla:h("mozilla"),isMoz:h("mozilla"),isOpera:h("opera"),isSafari:h("safari"),isChrome:h("chrome"),isMac:h("mac"),isIos:h("ios"),isAndroid:h("android"),isWii:h("wii"),isQuirks:h("quirks"),isAir:h("air")});return h})},"dojo/io-query":function(){define(["./_base/lang"],function(b){var m={};return{objectToQuery:function(h){var k=encodeURIComponent,e=[],c;for(c in h){var n=h[c];if(n!=m[c]){var a=k(c)+"\x3d";if(b.isArray(n))for(var g=0,d=n.length;g<d;++g)e.push(a+k(n[g]));else e.push(a+
k(n))}}return e.join("\x26")},queryToObject:function(h){var k=decodeURIComponent;h=h.split("\x26");for(var e={},c,n,a=0,g=h.length;a<g;++a)if(n=h[a],n.length){var d=n.indexOf("\x3d");0>d?(c=k(n),n=""):(c=k(n.slice(0,d)),n=k(n.slice(d+1)));"string"==typeof e[c]&&(e[c]=[e[c]]);b.isArray(e[c])?e[c].push(n):e[c]=n}return e}}})},"dojo/dom":function(){define(["./sniff","./_base/window","./_base/kernel"],function(b,m,h){if(7>=b("ie"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(c){}var k=
{};b("ie")?k.byId=function(c,b){if("string"!=typeof c)return c||null;var a=b||m.doc,g=c&&a.getElementById(c);if(!g||g.attributes.id.value!=c&&g.id!=c){a=a.all[c];if(!a||a.nodeName)a=[a];for(var d=0;g=a[d++];)if(g.attributes&&g.attributes.id&&g.attributes.id.value==c||g.id==c)return g}else return g;return null}:k.byId=function(c,b){return("string"==typeof c?(b||m.doc).getElementById(c):c)||null};h=h.global.document||null;b.add("dom-contains",!(!h||!h.contains));k.isDescendant=b("dom-contains")?function(c,
b){return!(!(b=k.byId(b))||!b.contains(k.byId(c)))}:function(c,b){try{for(c=k.byId(c),b=k.byId(b);c;){if(c==b)return!0;c=c.parentNode}}catch(a){}return!1};b.add("css-user-select",function(c,b,a){if(!a)return!1;c=a.style;b=["Khtml","O","Moz","Webkit"];a=b.length;var g="userSelect";do if("undefined"!==typeof c[g])return g;while(a--&&(g=b[a]+"UserSelect"));return!1});var e=b("css-user-select");k.setSelectable=e?function(c,b){k.byId(c).style[e]=b?"":"none"}:function(c,b){c=k.byId(c);var a=c.getElementsByTagName("*"),
g=a.length;if(b)for(c.removeAttribute("unselectable");g--;)a[g].removeAttribute("unselectable");else for(c.setAttribute("unselectable","on");g--;)a[g].setAttribute("unselectable","on")};return k})},"dojo/_base/window":function(){define(["./kernel","./lang","../sniff"],function(b,m,h){var k={global:b.global,doc:b.global.document||null,body:function(e){e=e||b.doc;return e.body||e.getElementsByTagName("body")[0]},setContext:function(e,c){b.global=k.global=e;b.doc=k.doc=c},withGlobal:function(e,c,h,a){var g=
b.global;try{return b.global=k.global=e,k.withDoc.call(null,e.document,c,h,a)}finally{b.global=k.global=g}},withDoc:function(e,c,n,a){var g=k.doc,d=h("quirks"),f=h("ie"),r,l,m;try{return b.doc=k.doc=e,b.isQuirks=h.add("quirks","BackCompat"==b.doc.compatMode,!0,!0),h("ie")&&(m=e.parentWindow)&&m.navigator&&(r=parseFloat(m.navigator.appVersion.split("MSIE ")[1])||void 0,(l=e.documentMode)&&5!=l&&Math.floor(r)!=l&&(r=l),b.isIE=h.add("ie",r,!0,!0)),n&&"string"==typeof c&&(c=n[c]),c.apply(n,a||[])}finally{b.doc=
k.doc=g,b.isQuirks=h.add("quirks",d,!0,!0),b.isIE=h.add("ie",f,!0,!0)}}};m.mixin(b,k);return k})},"dojo/dom-form":function(){define(["./_base/lang","./dom","./io-query","./json"],function(b,m,h,k){var e={fieldToObject:function(c){var b=null;if(c=m.byId(c)){var a=c.name,g=(c.type||"").toLowerCase();if(a&&g&&!c.disabled)if("radio"==g||"checkbox"==g)c.checked&&(b=c.value);else if(c.multiple)for(b=[],c=[c.firstChild];c.length;)for(a=c.pop();a;a=a.nextSibling)if(1==a.nodeType&&"option"==a.tagName.toLowerCase())a.selected&&
b.push(a.value);else{a.nextSibling&&c.push(a.nextSibling);a.firstChild&&c.push(a.firstChild);break}else b=c.value}return b},toObject:function(c){var h={};c=m.byId(c).elements;for(var a=0,g=c.length;a<g;++a){var d=c[a],f=d.name,k=(d.type||"").toLowerCase();if(f&&k&&0>"file|submit|image|reset|button".indexOf(k)&&!d.disabled){var l=h,C=f,d=e.fieldToObject(d);if(null!==d){var u=l[C];"string"==typeof u?l[C]=[u,d]:b.isArray(u)?u.push(d):l[C]=d}"image"==k&&(h[f+".x"]=h[f+".y"]=h[f].x=h[f].y=0)}}return h},
toQuery:function(c){return h.objectToQuery(e.toObject(c))},toJson:function(c,b){return k.stringify(e.toObject(c),null,b?4:0)}};return e})},"dojo/json":function(){define(["./has"],function(b){var m="undefined"!=typeof JSON;b.add("json-parse",m);b.add("json-stringify",m&&'{"a":1}'==JSON.stringify({a:0},function(b,e){return e||1}));if(b("json-stringify"))return JSON;var h=function(b){return('"'+b.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,
"\\t").replace(/[\r]/g,"\\r")};return{parse:b("json-parse")?JSON.parse:function(b,e){if(e&&!/^([\s\[\{]*(?:"(?:\\.|[^"])*"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(b))throw new SyntaxError("Invalid characters in JSON");return eval("("+b+")")},stringify:function(b,e,c){function k(b,d,f){e&&(b=e(f,b));var g;g=typeof b;if("number"==g)return isFinite(b)?b+"":"null";if("boolean"==g)return b+"";if(null===b)return"null";if("string"==typeof b)return h(b);if("function"==g||
"undefined"==g)return a;if("function"==typeof b.toJSON)return k(b.toJSON(f),d,f);if(b instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(a,c,d){a=b["getUTC"+c]()+(d?1:0);return 10>a?"0"+a:a});if(b.valueOf()!==b)return k(b.valueOf(),d,f);var l=c?d+c:"",n=c?" ":"",u=c?"\n":"";if(b instanceof Array){var n=b.length,x=[];for(f=0;f<n;f++)g=k(b[f],l,f),"string"!=typeof g&&(g="null"),x.push(u+l+g);return"["+x.join(",")+u+d+"]"}x=[];for(f in b){var m;
if(b.hasOwnProperty(f)){if("number"==typeof f)m='"'+f+'"';else if("string"==typeof f)m=h(f);else continue;g=k(b[f],l,f);"string"==typeof g&&x.push(u+l+m+":"+n+g)}}return"{"+x.join(",")+u+d+"}"}var a;"string"==typeof e&&(c=e,e=null);return k(b,"","")}}})},"dojo/_base/Deferred":function(){define("./kernel ../Deferred ../promise/Promise ../errors/CancelError ../has ./lang ../when".split(" "),function(b,m,h,k,e,c,n){var a=function(){},g=Object.freeze||function(){},d=b.Deferred=function(b){function f(a){if(u)throw Error("This deferred has already been resolved");
n=a;u=!0;l()}function l(){for(var b;!b&&w;){var d=w;w=w.next;if(b=d.progress==a)u=!1;var f=y?d.error:d.resolved;e("config-useDeferredInstrumentation")&&y&&m.instrumentRejected&&m.instrumentRejected(n,!!f);if(f)try{var g=f(n);g&&"function"===typeof g.then?g.then(c.hitch(d.deferred,"resolve"),c.hitch(d.deferred,"reject"),c.hitch(d.deferred,"progress")):(f=b&&void 0===g,b&&!f&&(y=g instanceof Error),d.deferred[f&&y?"reject":"resolve"](f?n:g))}catch(F){d.deferred.reject(F)}else y?d.deferred.reject(n):
d.deferred.resolve(n)}}var n,u,x,z,y,t,w,A=this.promise=new h;this.isResolved=A.isResolved=function(){return 0==z};this.isRejected=A.isRejected=function(){return 1==z};this.isFulfilled=A.isFulfilled=function(){return 0<=z};this.isCanceled=A.isCanceled=function(){return x};this.resolve=this.callback=function(a){this.fired=z=0;this.results=[a,null];f(a)};this.reject=this.errback=function(a){y=!0;this.fired=z=1;e("config-useDeferredInstrumentation")&&m.instrumentRejected&&m.instrumentRejected(a,!!w);
f(a);this.results=[null,a]};this.progress=function(a){for(var c=w;c;){var b=c.progress;b&&b(a);c=c.next}};this.addCallbacks=function(c,b){this.then(c,b,a);return this};A.then=this.then=function(c,b,f){var g=f==a?this:new d(A.cancel);c={resolved:c,error:b,progress:f,deferred:g};w?t=t.next=c:w=t=c;u&&l();return g.promise};var E=this;A.cancel=this.cancel=function(){if(!u){var a=b&&b(E);u||(a instanceof Error||(a=new k(a)),a.log=!1,E.reject(a))}x=!0};g(A)};c.extend(d,{addCallback:function(a){return this.addCallbacks(c.hitch.apply(b,
arguments))},addErrback:function(a){return this.addCallbacks(null,c.hitch.apply(b,arguments))},addBoth:function(a){var d=c.hitch.apply(b,arguments);return this.addCallbacks(d,d)},fired:-1});d.when=b.when=n;return d})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","./promise/instrumentation"],function(b,m,h,k,e){var c=Object.freeze||function(){},n=function(c,b,d,g,e){2===b&&f.instrumentRejected&&0===c.length&&f.instrumentRejected(d,!1,g,e);for(e=
0;e<c.length;e++)a(c[e],b,d,g)},a=function(a,c,b,e){var l=a[c],h=a.deferred;if(l)try{var k=l(b);if(0===c)"undefined"!==typeof k&&d(h,c,k);else{if(k&&"function"===typeof k.then){a.cancel=k.cancel;k.then(g(h,1),g(h,2),g(h,0));return}d(h,1,k)}}catch(t){d(h,2,t)}else d(h,c,b);2===c&&f.instrumentRejected&&f.instrumentRejected(b,!!l,e,h.promise)},g=function(a,c){return function(b){d(a,c,b)}},d=function(a,c,b){if(!a.isCanceled())switch(c){case 0:a.progress(b);break;case 1:a.resolve(b);break;case 2:a.reject(b)}},
f=function(b){var d=this.promise=new k,g=this,e,r,m,y=!1,t=[];Error.captureStackTrace&&(Error.captureStackTrace(g,f),Error.captureStackTrace(d,f));this.isResolved=d.isResolved=function(){return 1===e};this.isRejected=d.isRejected=function(){return 2===e};this.isFulfilled=d.isFulfilled=function(){return!!e};this.isCanceled=d.isCanceled=function(){return y};this.progress=function(a,c){if(e){if(!0===c)throw Error("This deferred has already been fulfilled.");return d}n(t,0,a,null,g);return d};this.resolve=
function(a,c){if(e){if(!0===c)throw Error("This deferred has already been fulfilled.");return d}n(t,e=1,r=a,null,g);t=null;return d};var w=this.reject=function(a,c){if(e){if(!0===c)throw Error("This deferred has already been fulfilled.");return d}Error.captureStackTrace&&Error.captureStackTrace(m={},w);n(t,e=2,r=a,m,g);t=null;return d};this.then=d.then=function(c,b,g){var h=[g,c,b];h.cancel=d.cancel;h.deferred=new f(function(a){return h.cancel&&h.cancel(a)});e&&!t?a(h,e,r,m):t.push(h);return h.deferred.promise};
this.cancel=d.cancel=function(a,c){if(!e){if(b){var d=b(a);a="undefined"===typeof d?a:d}y=!0;if(!e)return"undefined"===typeof a&&(a=new h),w(a),a;if(2===e&&r===a)return a}else if(!0===c)throw Error("This deferred has already been fulfilled.");};c(d)};f.prototype.toString=function(){return"[object Deferred]"};e&&e(f);return f})},"dojo/errors/CancelError":function(){define(["./create"],function(b){return b("CancelError",null,null,{dojoType:"cancel",log:!1})})},"dojo/errors/create":function(){define(["../_base/lang"],
function(b){return function(m,h,k,e){k=k||Error;var c=function(b){if(k===Error){Error.captureStackTrace&&Error.captureStackTrace(this,c);var a=Error.call(this,b),g;for(g in a)a.hasOwnProperty(g)&&(this[g]=a[g]);this.message=b;this.stack=a.stack}else k.apply(this,arguments);h&&h.apply(this,arguments)};c.prototype=b.delegate(k.prototype,e);c.prototype.name=m;return c.prototype.constructor=c}})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(b){function m(){throw new TypeError("abstract");
}return b.extend(function(){},{then:function(b,k,e){m()},cancel:function(b,k){m()},isResolved:function(){m()},isRejected:function(){m()},isFulfilled:function(){m()},isCanceled:function(){m()},"finally":function(b){return this.then(function(h){var e=b();return e&&"function"===typeof e.then?e.then(function(){return h}):h},function(h){var e=b();if(e&&"function"===typeof e.then)return e.then(function(){throw h;});throw h;})},always:function(b){return this.then(b,b)},"catch":function(b){return this.then(null,
b)},otherwise:function(b){return this.then(null,b)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/promise/instrumentation":function(){define(["./tracer","../has","../_base/lang","../_base/array"],function(b,m,h,k){function e(a,c,b){if(!a||!1!==a.log){var d="";a&&a.stack&&(d+=a.stack);c&&c.stack&&(d+="\n    ----------------------------------------\n    rejected"+c.stack.split("\n").slice(1).join("\n").replace(/^\s+/," "));
b&&b.stack&&(d+="\n    ----------------------------------------\n"+b.stack);console.error(a,d)}}function c(a,c,b,d){c||e(a,b,d)}function n(c,b,e,h){k.some(g,function(a){if(a.error===c)return b&&(a.handled=!0),!0})||g.push({error:c,rejection:e,handled:b,deferred:h,timestamp:(new Date).getTime()});d||(d=setTimeout(a,f))}function a(){var c=(new Date).getTime(),b=c-f;g=k.filter(g,function(a){return a.timestamp<b?(a.handled||e(a.error,a.rejection,a.deferred),!1):!0});d=g.length?setTimeout(a,g[0].timestamp+
f-c):!1}m.add("config-useDeferredInstrumentation","report-unhandled-rejections");var g=[],d=!1,f=1E3;return function(a){var d=m("config-useDeferredInstrumentation");if(d){b.on("resolved",h.hitch(console,"log","resolved"));b.on("rejected",h.hitch(console,"log","rejected"));b.on("progress",h.hitch(console,"log","progress"));var g=[];"string"===typeof d&&(g=d.split(","),d=g.shift());if("report-rejections"===d)a.instrumentRejected=c;else if("report-unhandled-rejections"===d||!0===d||1===d)a.instrumentRejected=
n,f=parseInt(g[0],10)||f;else throw Error("Unsupported instrumentation usage \x3c"+d+"\x3e");}}})},"dojo/promise/tracer":function(){define(["../_base/lang","./Promise","../Evented"],function(b,m,h){function k(b){setTimeout(function(){c.apply(e,b)},0)}var e=new h,c=e.emit;e.emit=null;m.prototype.trace=function(){var c=b._toArray(arguments);this.then(function(a){k(["resolved",a].concat(c))},function(a){k(["rejected",a].concat(c))},function(a){k(["progress",a].concat(c))});return this};m.prototype.traceRejected=
function(){var c=b._toArray(arguments);this.otherwise(function(a){k(["rejected",a].concat(c))});return this};return e})},"dojo/Evented":function(){define(["./aspect","./on"],function(b,m){function h(){}var k=b.after;h.prototype={on:function(b,c){return m.parse(this,b,c,function(b,a){return k(b,"on"+a,c,!0)})},emit:function(b,c){var e=[this];e.push.apply(e,arguments);return m.emit.apply(m,e)}};return h})},"dojo/aspect":function(){define([],function(){function b(c,a,b,d){var f=c[a],g="around"==a,e;
if(g){var h=b(function(){return f.advice(this,arguments)});e={remove:function(){h&&(h=c=b=null)},advice:function(a,c){return h?h.apply(a,c):f.advice(a,c)}}}else e={remove:function(){if(e.advice){var d=e.previous,f=e.next;f||d?(d?d.next=f:c[a]=f,f&&(f.previous=d)):delete c[a];c=b=e.advice=null}},id:c.nextId++,advice:b,receiveArguments:d};if(f&&!g)if("after"==a){for(;f.next&&(f=f.next););f.next=e;e.previous=f}else"before"==a&&(c[a]=e,e.next=f,f.previous=e);else c[a]=e;return e}function m(c){return function(a,
g,d,f){var e=a[g],k;e&&e.target==a||(a[g]=k=function(){for(var a=k.nextId,c=arguments,b=k.before;b;)b.advice&&(c=b.advice.apply(this,c)||c),b=b.next;if(k.around)var d=k.around.advice(this,c);for(b=k.after;b&&b.id<a;){if(b.advice)if(b.receiveArguments)var f=b.advice.apply(this,c),d=f===h?d:f;else d=b.advice.call(this,d,c);b=b.next}return d},e&&(k.around={advice:function(a,c){return e.apply(a,c)}}),k.target=a,k.nextId=k.nextId||0);a=b(k||e,c,d,f);d=null;return a}}var h,k=m("after"),e=m("before"),c=
m("around");return{before:e,around:c,after:k}})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(b,m,h){function k(c,b,d,f,e){if(f=b.match(/(.*):(.*)/))return b=f[2],f=f[1],a.selector(f,b).call(e,c,d);h("touch")&&(g.test(b)&&(d=q(d)),h("event-orientationchange")||"orientationchange"!=b||(b="resize",c=window,d=q(d)));C&&(d=C(d));if(c.addEventListener){var k=b in r,l=k?r[b]:b;c.addEventListener(l,d,k);return{remove:function(){c.removeEventListener(l,
d,k)}}}if(y&&c.attachEvent)return y(c,"on"+b,d);throw Error("Target must be an event emitter");}function e(){this.cancelable=!1;this.defaultPrevented=!0}function c(){this.bubbles=!1}var n=window.ScriptEngineMajorVersion;h.add("jscript",n&&n()+ScriptEngineMinorVersion()/10);h.add("event-orientationchange",h("touch")&&!h("android"));h.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);h.add("event-focusin",function(a,c,b){return"onfocusin"in
b});h("touch")&&h.add("touch-can-modify-event-delegate",function(){var a=function(){};a.prototype=document.createEvent("MouseEvents");try{var c=new a;c.target=null;return null===c.target}catch(v){return!1}});var a=function(c,b,d,f){return"function"!=typeof c.on||"function"==typeof b||c.nodeType?a.parse(c,b,d,k,f,this):c.on(b,d)};a.pausable=function(c,b,d,f){var g;c=a(c,b,function(){if(!g)return d.apply(this,arguments)},f);c.pause=function(){g=!0};c.resume=function(){g=!1};return c};a.once=function(c,
b,d,f){var g=a(c,b,function(){g.remove();return d.apply(this,arguments)});return g};a.parse=function(c,b,d,f,g,e){var h;if(b.call)return b.call(e,c,d);b instanceof Array?h=b:-1<b.indexOf(",")&&(h=b.split(/\s*,\s*/));if(h){var k=[];b=0;for(var l;l=h[b++];)k.push(a.parse(c,l,d,f,g,e));k.remove=function(){for(var a=0;a<k.length;a++)k[a].remove()};return k}return f(c,b,d,g,e)};var g=/^touch/;a.matches=function(a,c,b,d,f){f=f&&"function"==typeof f.matches?f:m.query;d=!1!==d;1!=a.nodeType&&(a=a.parentNode);
for(;!f.matches(a,c,b);)if(a==b||!1===d||!(a=a.parentNode)||1!=a.nodeType)return!1;return a};a.selector=function(c,b,d){return function(f,g){function e(b){return a.matches(b,c,f,d,h)}var h="function"==typeof c?{matches:c}:this,k=b.bubble;return k?a(f,k(e),g):a(f,b,function(a){var c=e(a.target);if(c)return a.selectorTarget=c,g.call(c,a)})}};var d=[].slice,f=a.emit=function(a,b,f){var g=d.call(arguments,2),h="on"+b;if("parentNode"in a){var k=g[0]={},l;for(l in f)k[l]=f[l];k.preventDefault=e;k.stopPropagation=
c;k.target=a;k.type=b;f=k}do a[h]&&a[h].apply(a,g);while(f&&f.bubbles&&(a=a.parentNode));return f&&f.cancelable&&f},r=h("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!h("event-stopimmediatepropagation"))var l=function(){this.modified=this.immediatelyStopped=!0},C=function(a){return function(c){if(!c.immediatelyStopped)return c.stopImmediatePropagation=l,a.apply(this,arguments)}};if(h("dom-addeventlistener"))a.emit=function(c,b,d){if(c.dispatchEvent&&document.createEvent){var g=(c.ownerDocument||
document).createEvent("HTMLEvents");g.initEvent(b,!!d.bubbles,!!d.cancelable);for(var e in d)e in g||(g[e]=d[e]);return c.dispatchEvent(g)&&g}return f.apply(a,arguments)};else{a._fixEvent=function(a,c){a||(a=(c&&(c.ownerDocument||c.document||c).parentWindow||window).event);if(!a)return a;try{u&&a.type==u.type&&a.srcElement==u.target&&(a=u)}catch(F){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=c||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=
a.toElement),a.stopPropagation||(a.stopPropagation=t,a.preventDefault=w),a.type){case "keypress":var b="charCode"in a?a.charCode:a.keyCode;10==b?(b=0,a.keyCode=13):13==b||27==b?b=0:3==b&&(b=99);a.charCode=b;b=a;b.keyChar=b.charCode?String.fromCharCode(b.charCode):"";b.charOrCode=b.keyChar||b.keyCode}return a};var u,x=function(a){this.handle=a};x.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var z=function(c){return function(b){b=a._fixEvent(b,this);var d=c.call(this,b);b.modified&&
(u||setTimeout(function(){u=null}),u=b);return d}},y=function(a,c,d){d=z(d);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>h("jscript"))&&!h("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var f=a[c];if(!f||!f.listeners){var g=f,f=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");
f.listeners=[];a[c]=f;f.global=this;g&&f.listeners.push(_dojoIEListeners_.push(g)-1)}f.listeners.push(a=f.global._dojoIEListeners_.push(d)-1);return new x(a)}return b.after(a,c,d,!0)},t=function(){this.cancelBubble=!0},w=a._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(p){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(h("touch"))var A=function(){},E=window.orientation,q=function(a){return function(c){var b=c.corrected;if(!b){var d=
c.type;try{delete c.type}catch(S){}if(c.type){if(h("touch-can-modify-event-delegate"))A.prototype=c,b=new A;else{var b={},f;for(f in c)b[f]=c[f]}b.preventDefault=function(){c.preventDefault()};b.stopPropagation=function(){c.stopPropagation()}}else b=c,b.type=d;c.corrected=b;if("resize"==d){if(E==window.orientation)return null;E=window.orientation;b.type="orientationchange";return a.call(this,b)}"rotation"in b||(b.rotation=0,b.scale=1);if(window.TouchEvent&&c instanceof TouchEvent){var d=b.changedTouches[0],
g;for(g in d)delete b[g],b[g]=d[g]}}return a.call(this,b)}};return a})},"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(b,m){return function(h,k,e,c){var n=h&&"function"===typeof h.then,a=n&&h instanceof m;if(!n)return 1<arguments.length?k?k(h):h:(new b).resolve(h);a||(n=new b(h.cancel),h.then(n.resolve,n.reject,n.progress),h=n.promise);return k||e||c?h.then(k,e,c):h}})},"dojo/_base/json":function(){define(["./kernel","../json"],function(b,m){b.fromJson=function(b){return eval("("+
b+")")};b._escapeString=m.stringify;b.toJsonIndentStr="\t";b.toJson=function(h,k){return m.stringify(h,function(b,c){if(c){var e=c.__json__||c.json;if("function"==typeof e)return e.call(c)}return c},k&&b.toJsonIndentStr)};return b})},"dojo/request/watch":function(){define("./util ../errors/RequestTimeoutError ../errors/CancelError ../_base/array ../_base/window ../has!host-browser?dom-addeventlistener?:../on:".split(" "),function(b,m,h,k,e,c){function n(){for(var c=+new Date,b=0,e;b<d.length&&(e=
d[b]);b++){var h=e.response,k=h.options;e.isCanceled&&e.isCanceled()||e.isValid&&!e.isValid(h)?(d.splice(b--,1),a._onAction&&a._onAction()):e.isReady&&e.isReady(h)?(d.splice(b--,1),e.handleResponse(h),a._onAction&&a._onAction()):e.startTime&&e.startTime+(k.timeout||0)<c&&(d.splice(b--,1),e.cancel(new m("Timeout exceeded",h)),a._onAction&&a._onAction())}a._onInFlight&&a._onInFlight(e);d.length||(clearInterval(g),g=null)}function a(a){a.response.options.timeout&&(a.startTime=+new Date);a.isFulfilled()||
(d.push(a),g||(g=setInterval(n,50)),a.response.options.sync&&n())}var g=null,d=[];a.cancelAll=function(){try{k.forEach(d,function(a){try{a.cancel(new h("All requests canceled."))}catch(r){}})}catch(f){}};e&&c&&e.doc.attachEvent&&c(e.global,"unload",function(){a.cancelAll()});return a})},"dojo/request/util":function(){define("exports ../errors/RequestError ../errors/CancelError ../Deferred ../io-query ../_base/array ../_base/lang ../promise/Promise ../has".split(" "),function(b,m,h,k,e,c,n,a,g){function d(a){return g("native-arraybuffer")&&
a instanceof ArrayBuffer}function f(a){return g("native-blob")&&a instanceof Blob}function r(a){return C(a)}function l(a){return void 0!==a.data?a.data:a.text}b.deepCopy=function(a,c){for(var e in c){var h=a[e],k=c[e];if("__proto__"!==e&&h!==k){var l=k,m;(m=!l||"object"!==typeof l)||(m=l,m=g("native-formdata")&&m instanceof FormData);m||("undefined"!==typeof Element?l instanceof Element:1===l.nodeType)||f(l)||d(l)?a[e]=k:"[object Date]"===Object.prototype.toString.call(k)?a[e]=new Date(k):n.isArray(k)?
a[e]=b.deepCopyArray(k):h&&"object"===typeof h?b.deepCopy(h,k):a[e]=b.deepCopy({},k)}}return a};b.deepCopyArray=function(a){for(var c=[],d=0,f=a.length;d<f;d++){var g=a[d];"object"===typeof g?c.push(b.deepCopy({},g)):c.push(g)}return c};b.deepCreate=function(a,c){c=c||{};var d=n.delegate(a),f,g;for(f in a)(g=a[f])&&"object"===typeof g&&(d[f]=b.deepCreate(g,c[f]));return b.deepCopy(d,c)};var C=Object.freeze||function(a){return a};b.deferred=function(c,d,f,g,e,w){var x=new k(function(a){d&&d(x,c);return a&&
(a instanceof m||a instanceof h)?a:new h("Request canceled",c)});x.response=c;x.isValid=f;x.isReady=g;x.handleResponse=e;f=x.then(r).otherwise(function(a){a.response=c;throw a;});b.notify&&f.then(n.hitch(b.notify,"emit","load"),n.hitch(b.notify,"emit","error"));g=f.then(l);e=new a;for(var t in g)g.hasOwnProperty(t)&&(e[t]=g[t]);e.response=f;C(e);w&&x.then(function(a){w.call(x,a)},function(a){w.call(x,c,a)});x.promise=e;x.then=e.then;return x};b.addCommonMethods=function(a,b){c.forEach(b||["GET","POST",
"PUT","DELETE"],function(c){a[("DELETE"===c?"DEL":c).toLowerCase()]=function(b,d){d=n.delegate(d||{});d.method=c;return a(b,d)}})};b.parseArgs=function(a,c,b){var h=c.data,k=c.query;!h||b||"object"!==typeof h||g("native-xhr2")&&(d(h)||f(h))||(c.data=e.objectToQuery(h));k?("object"===typeof k&&(k=e.objectToQuery(k)),c.preventCache&&(k+=(k?"\x26":"")+"request.preventCache\x3d"+ +new Date)):c.preventCache&&(k="request.preventCache\x3d"+ +new Date);a&&k&&(a+=(~a.indexOf("?")?"\x26":"?")+k);return{url:a,
options:c,getHeader:function(a){return null}}};b.checkStatus=function(a){a=a||0;return 200<=a&&300>a||304===a||1223===a||!a}})},"dojo/errors/RequestError":function(){define(["./create"],function(b){return b("RequestError",function(b,h){this.response=h})})},"dojo/errors/RequestTimeoutError":function(){define(["./create","./RequestError"],function(b,m){return b("RequestTimeoutError",null,m,{dojoType:"timeout"})})},"dojo/request/xhr":function(){define(["../errors/RequestError","./watch","./handlers",
"./util","../has"],function(b,m,h,k,e){function c(a,c){var d=a.xhr;a.status=a.xhr.status;try{a.text=d.responseText}catch(w){}"xml"===a.options.handleAs&&(a.data=d.responseXML);var f;if(c)this.reject(c);else{try{h(a)}catch(w){f=w}k.checkStatus(d.status)?f?this.reject(f):this.resolve(a):(c=f?new b("Unable to load "+a.url+" status: "+d.status+" and an error in handleAs: transformation of response",a):new b("Unable to load "+a.url+" status: "+d.status,a),this.reject(c))}}function n(a){return this.xhr.getResponseHeader(a)}
function a(h,z,y){var x=e("native-formdata")&&z&&z.data&&z.data instanceof FormData,w=k.parseArgs(h,k.deepCreate(u,z),x);h=w.url;z=w.options;var A=!z.data&&"POST"!==z.method&&"PUT"!==z.method;10>=e("ie")&&(h=h.split("#")[0]);var E,q=k.deferred(w,l,d,f,c,function(){E&&E()}),p=w.xhr=a._create();if(!p)return q.cancel(new b("XHR was not created")),y?q:q.promise;w.getHeader=n;r&&(E=r(p,q,w,z.uploadProgress));var J="undefined"===typeof z.data?null:z.data,v=!z.sync,F=z.method;try{p.open(F,h,v,z.user||C,
z.password||C);z.withCredentials&&(p.withCredentials=z.withCredentials);e("native-response-type")&&z.handleAs in g&&(p.responseType=g[z.handleAs]);var D=z.headers;h=x||A?!1:"application/x-www-form-urlencoded";if(D)for(var M in D)"content-type"===M.toLowerCase()?h=D[M]:D[M]&&p.setRequestHeader(M,D[M]);h&&!1!==h&&p.setRequestHeader("Content-Type",h);D&&"X-Requested-With"in D||p.setRequestHeader("X-Requested-With","XMLHttpRequest");k.notify&&k.notify.emit("send",w,q.promise.cancel);p.send(J)}catch(S){q.reject(S)}m(q);
p=null;return y?q:q.promise}e.add("native-xhr",function(){return"undefined"!==typeof XMLHttpRequest});e.add("dojo-force-activex-xhr",function(){return e("activex")&&"file:"===window.location.protocol});e.add("native-xhr2",function(){if(e("native-xhr")&&!e("dojo-force-activex-xhr")){var a=new XMLHttpRequest;return"undefined"!==typeof a.addEventListener&&("undefined"===typeof opera||"undefined"!==typeof a.upload)}});e.add("native-formdata",function(){return"undefined"!==typeof FormData});e.add("native-blob",
function(){return"undefined"!==typeof Blob});e.add("native-arraybuffer",function(){return"undefined"!==typeof ArrayBuffer});e.add("native-response-type",function(){return e("native-xhr")&&"undefined"!==typeof(new XMLHttpRequest).responseType});e.add("native-xhr2-blob",function(){if(e("native-response-type")){var a=new XMLHttpRequest;a.open("GET","https://dojotoolkit.org/",!0);a.responseType="blob";var c=a.responseType;a.abort();return"blob"===c}});var g={blob:e("native-xhr2-blob")?"blob":"arraybuffer",
document:"document",arraybuffer:"arraybuffer"},d,f,r,l;e("native-xhr2")?(d=function(a){return!this.isFulfilled()},l=function(a,c){c.xhr.abort()},r=function(a,c,d,f){function g(a){c.handleResponse(d)}function e(a){a=new b("Unable to load "+d.url+" status: "+a.target.status,d);c.handleResponse(d,a)}function h(a,b){d.transferType=a;b.lengthComputable?(d.loaded=b.loaded,d.total=b.total,c.progress(d)):3===d.xhr.readyState&&(d.loaded="loaded"in b?b.loaded:b.position,c.progress(d))}function k(a){return h("download",
a)}function l(a){return h("upload",a)}a.addEventListener("load",g,!1);a.addEventListener("error",e,!1);a.addEventListener("progress",k,!1);f&&a.upload&&a.upload.addEventListener("progress",l,!1);return function(){a.removeEventListener("load",g,!1);a.removeEventListener("error",e,!1);a.removeEventListener("progress",k,!1);a.upload.removeEventListener("progress",l,!1);a=null}}):(d=function(a){return a.xhr.readyState},f=function(a){return 4===a.xhr.readyState},l=function(a,c){var b=c.xhr,d=typeof b.abort;
"function"!==d&&"object"!==d&&"unknown"!==d||b.abort()});var C,u={data:null,query:null,sync:!1,method:"GET"};a._create=function(){throw Error("XMLHTTP not available");};if(e("native-xhr")&&!e("dojo-force-activex-xhr"))a._create=function(){return new XMLHttpRequest};else if(e("activex"))try{new ActiveXObject("Msxml2.XMLHTTP"),a._create=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(x){try{new ActiveXObject("Microsoft.XMLHTTP"),a._create=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(z){}}k.addCommonMethods(a);
return a})},"dojo/request/handlers":function(){define(["../json","../_base/kernel","../_base/array","../has","../selector/_loader"],function(b,m,h,k){function e(a){var c=d[a.options.handleAs];a.data=c?c(a):a.data||a.text;return a}k.add("activex","undefined"!==typeof ActiveXObject);k.add("dom-parser",function(a){return"DOMParser"in a});var c;if(k("activex")){var n=["Msxml2.DOMDocument.6.0","Msxml2.DOMDocument.4.0","MSXML2.DOMDocument.3.0","MSXML.DOMDocument"],a;c=function(c){function b(c){try{var b=
new ActiveXObject(c);b.async=!1;b.loadXML(f);d=b;a=c}catch(z){return!1}return!0}var d=c.data,f=c.text;d&&k("dom-qsa2.1")&&!d.querySelectorAll&&k("dom-parser")&&(d=(new DOMParser).parseFromString(f,"application/xml"));d&&d.documentElement||a&&b(a)||h.some(n,b);return d}}var g=function(a){return k("native-xhr2-blob")||"blob"!==a.options.handleAs||"undefined"===typeof Blob?a.xhr.response:new Blob([a.xhr.response],{type:a.xhr.getResponseHeader("Content-Type")})},d={javascript:function(a){return m.eval(a.text||
"")},json:function(a){return b.parse(a.text||null)},xml:c,blob:g,arraybuffer:g,document:g};e.register=function(a,c){d[a]=c};return e})},"dojo/selector/_loader":function(){define(["../has","require"],function(b,m){if("undefined"!==typeof document){var h=document.createElement("div");b.add("dom-qsa2.1",!!h.querySelectorAll);b.add("dom-qsa3",function(){try{return h.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e",1==h.querySelectorAll(".TEST:empty").length}catch(e){}})}var k;return{load:function(e,c,
h,a){if(a&&a.isBuild)h();else{a=m;e="default"==e?b("config-selectorEngine")||"css3":e;e="css2"==e||"lite"==e?"./lite":"css2.1"==e?b("dom-qsa2.1")?"./lite":"./acme":"css3"==e?b("dom-qsa3")?"./lite":"./acme":"acme"==e?"./acme":(a=c)&&e;if("?"==e.charAt(e.length-1)){e=e.substring(0,e.length-1);var g=!0}if(g&&(b("dom-compliant-qsa")||k))return h(k);a([e],function(a){"./lite"!=e&&(k=a);h(a)})}}}})},"dojo/regexp":function(){define(["./_base/kernel","./_base/lang"],function(b,m){var h={};m.setObject("dojo.regexp",
h);h.escapeString=function(b,e){return b.replace(/([\.$?*|{}\(\)\[\]\\\/\+\-^])/g,function(c){return e&&-1!=e.indexOf(c)?c:"\\"+c})};h.buildGroupRE=function(b,e,c){if(!(b instanceof Array))return e(b);for(var k=[],a=0;a<b.length;a++)k.push(e(b[a]));return h.group(k.join("|"),c)};h.group=function(b,e){return"("+(e?"?:":"")+b+")"};return h})},"dojo/string":function(){define(["./_base/kernel","./_base/lang"],function(b,m){var h=/[&<>'"\/]/g,k={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;",
"'":"\x26#x27;","/":"\x26#x2F;"},e={};m.setObject("dojo.string",e);e.escape=function(c){return c?c.replace(h,function(c){return k[c]}):""};e.rep=function(c,b){if(0>=b||!c)return"";for(var a=[];;){b&1&&a.push(c);if(!(b>>=1))break;c+=c}return a.join("")};e.pad=function(c,b,a,g){a||(a="0");c=String(c);b=e.rep(a,Math.ceil((b-c.length)/a.length));return g?c+b:b+c};e.substitute=function(c,e,a,g){g=g||b.global;a=a?m.hitch(g,a):function(a){return a};return c.replace(/\$\{([^\s\:\}]*)(?:\:([^\s\:\}]+))?\}/g,
function(c,b,h){if(""==b)return"$";c=m.getObject(b,!1,e);h&&(c=m.getObject(h,!1,g).call(g,c,b));h=a(c,b);if("undefined"===typeof h)throw Error('string.substitute could not find key "'+b+'" in template');return h.toString()})};e.trim=String.prototype.trim?m.trim:function(c){c=c.replace(/^\s+/,"");for(var b=c.length-1;0<=b;b--)if(/\S/.test(c.charAt(b))){c=c.substring(0,b+1);break}return c};return e})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(b,m){var h={};b.setObject("dojo.date.stamp",
h);h.fromISOString=function(b,e){h._isoRegExp||(h._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var c=h._isoRegExp.exec(b),k=null;if(c){c.shift();c[1]&&c[1]--;c[6]&&(c[6]*=1E3);e&&(e=new Date(e),m.forEach(m.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return e["get"+a]()}),function(a,b){c[b]=c[b]||a}));k=new Date(c[0]||1970,c[1]||0,c[2]||1,c[3]||0,c[4]||0,c[5]||0,c[6]||0);100>c[0]&&
k.setFullYear(c[0]||1970);var a=0,g=c[7]&&c[7].charAt(0);"Z"!=g&&(a=60*(c[8]||0)+(Number(c[9])||0),"-"!=g&&(a*=-1));g&&(a-=k.getTimezoneOffset());a&&k.setTime(k.getTime()+6E4*a)}return k};h.toISOString=function(b,e){var c=function(a){return 10>a?"0"+a:a};e=e||{};var h=[],a=e.zulu?"getUTC":"get",g="";"time"!=e.selector&&(g=b[a+"FullYear"](),g=["0000".substr((g+"").length)+g,c(b[a+"Month"]()+1),c(b[a+"Date"]())].join("-"));h.push(g);if("date"!=e.selector){g=[c(b[a+"Hours"]()),c(b[a+"Minutes"]()),c(b[a+
"Seconds"]())].join(":");a=b[a+"Milliseconds"]();e.milliseconds&&(g+="."+(100>a?"0":"")+c(a));if(e.zulu)g+="Z";else if("time"!=e.selector)var a=b.getTimezoneOffset(),d=Math.abs(a),g=g+((0<a?"-":"+")+c(Math.floor(d/60))+":"+c(d%60));h.push(g)}return h.join("T")};return h})},"dojo/number":function(){define(["./_base/lang","./i18n","./i18n!./cldr/nls/number","./string","./regexp"],function(b,m,h,k,e){var c={};b.setObject("dojo.number",c);c.format=function(a,g){g=b.mixin({},g||{});var d=m.normalizeLocale(g.locale),
d=m.getLocalization("dojo.cldr","number",d);g.customs=d;d=g.pattern||d[(g.type||"decimal")+"Format"];return isNaN(a)||Infinity==Math.abs(a)?null:c._applyPattern(a,d,g)};c._numberPatternRE=/[#0,]*[#0](?:\.0*#*)?/;c._applyPattern=function(a,b,d){d=d||{};var f=d.customs.group,g=d.customs.decimal;b=b.split(";");var e=b[0];b=b[0>a?1:0]||"-"+e;if(-1!=b.indexOf("%"))a*=100;else if(-1!=b.indexOf("\u2030"))a*=1E3;else if(-1!=b.indexOf("\u00a4"))f=d.customs.currencyGroup||f,g=d.customs.currencyDecimal||g,b=
b.replace(/([\s\xa0]*)(\u00a4{1,3})([\s\xa0]*)/,function(a,c,b,f){return(a=d[["symbol","currency","displayName"][b.length-1]]||d.currency||"")?c+a+f:""});else if(-1!=b.indexOf("E"))throw Error("exponential notation not supported");var h=c._numberPatternRE,e=e.match(h);if(!e)throw Error("unable to find a number expression in pattern: "+b);!1===d.fractional&&(d.places=0);return b.replace(h,c._formatAbsolute(a,e[0],{decimal:g,group:f,places:d.places,round:d.round}))};c.round=function(a,c,b){b=10/(b||
10);return(b*+a).toFixed(c)/b};if(0==(.9).toFixed()){var n=c.round;c.round=function(a,c,b){var d=Math.pow(10,-c||0),e=Math.abs(a);if(!a||e>=d)d=0;else if(e/=d,.5>e||.95<=e)d=0;return n(a,c,b)+(0<a?d:-d)}}c._formatAbsolute=function(a,b,d){d=d||{};!0===d.places&&(d.places=0);Infinity===d.places&&(d.places=6);b=b.split(".");var f="string"==typeof d.places&&d.places.indexOf(","),e=d.places;f?e=d.places.substring(f+1):0<=e||(e=(b[1]||[]).length);0>d.round||(a=c.round(a,e,d.round));a=String(Math.abs(a)).split(".");
var g=a[1]||"";b[1]||d.places?(f&&(d.places=d.places.substring(0,f)),f=void 0!==d.places?d.places:b[1]&&b[1].lastIndexOf("0")+1,f>g.length&&(a[1]=k.pad(g,f,"0",!0)),e<g.length&&(a[1]=g.substr(0,e))):a[1]&&a.pop();e=b[0].replace(",","");f=e.indexOf("0");-1!=f&&(f=e.length-f,f>a[0].length&&(a[0]=k.pad(a[0],f)),-1==e.indexOf("#")&&(a[0]=a[0].substr(a[0].length-f)));var e=b[0].lastIndexOf(","),h,m;-1!=e&&(h=b[0].length-e-1,b=b[0].substr(0,e),e=b.lastIndexOf(","),-1!=e&&(m=b.length-e-1));b=[];for(e=a[0];e;)f=
e.length-h,b.push(0<f?e.substr(f):e),e=0<f?e.slice(0,f):"",m&&(h=m,m=void 0);a[0]=b.reverse().join(d.group||",");return a.join(d.decimal||".")};c.regexp=function(a){return c._parseInfo(a).regexp};c._parseInfo=function(a){a=a||{};var b=m.normalizeLocale(a.locale),b=m.getLocalization("dojo.cldr","number",b),d=a.pattern||b[(a.type||"decimal")+"Format"],f=b.group,h=b.decimal,k=1;if(-1!=d.indexOf("%"))k/=100;else if(-1!=d.indexOf("\u2030"))k/=1E3;else{var n=-1!=d.indexOf("\u00a4");n&&(f=b.currencyGroup||
f,h=b.currencyDecimal||h)}b=d.split(";");1==b.length&&b.push("-"+b[0]);b=e.buildGroupRE(b,function(b){b="(?:"+e.escapeString(b,".")+")";return b.replace(c._numberPatternRE,function(b){var d={signed:!1,separator:a.strict?f:[f,""],fractional:a.fractional,decimal:h,exponent:!1};b=b.split(".");var e=a.places;1==b.length&&1!=k&&(b[1]="###");1==b.length||0===e?d.fractional=!1:(void 0===e&&(e=a.pattern?b[1].lastIndexOf("0")+1:Infinity),e&&void 0==a.fractional&&(d.fractional=!0),!a.places&&e<b[1].length&&
(e+=","+b[1].length),d.places=e);b=b[0].split(",");1<b.length&&(d.groupSize=b.pop().length,1<b.length&&(d.groupSize2=b.pop().length));return"("+c._realNumberRegexp(d)+")"})},!0);n&&(b=b.replace(/([\s\xa0]*)(\u00a4{1,3})([\s\xa0]*)/g,function(b,c,d,f){b=e.escapeString(a[["symbol","currency","displayName"][d.length-1]]||a.currency||"");if(!b)return"";c=c?"[\\s\\xa0]":"";f=f?"[\\s\\xa0]":"";return a.strict?c+b+f:(c&&(c+="*"),f&&(f+="*"),"(?:"+c+b+f+")?")}));return{regexp:b.replace(/[\xa0 ]/g,"[\\s\\xa0]"),
group:f,decimal:h,factor:k}};c.parse=function(a,b){var d=c._parseInfo(b),e=(new RegExp("^"+d.regexp+"$")).exec(a);if(!e)return NaN;var g=e[1];if(!e[1]){if(!e[2])return NaN;g=e[2];d.factor*=-1}g=g.replace(new RegExp("["+d.group+"\\s\\xa0]","g"),"").replace(d.decimal,".");return g*d.factor};c._realNumberRegexp=function(a){a=a||{};"places"in a||(a.places=Infinity);"string"!=typeof a.decimal&&(a.decimal=".");"fractional"in a&&!/^0/.test(a.places)||(a.fractional=[!0,!1]);"exponent"in a||(a.exponent=[!0,
!1]);"eSigned"in a||(a.eSigned=[!0,!1]);var b=c._integerRegexp(a),d=e.buildGroupRE(a.fractional,function(b){var c="";b&&0!==a.places&&(c="\\"+a.decimal,c=Infinity==a.places?"(?:"+c+"\\d+)?":c+("\\d{"+a.places+"}"));return c},!0),f=e.buildGroupRE(a.exponent,function(b){return b?"([eE]"+c._integerRegexp({signed:a.eSigned})+")":""}),b=b+d;d&&(b="(?:(?:"+b+")|(?:"+d+"))");return b+f};c._integerRegexp=function(a){a=a||{};"signed"in a||(a.signed=[!0,!1]);"separator"in a?"groupSize"in a||(a.groupSize=3):
a.separator="";var b=e.buildGroupRE(a.signed,function(a){return a?"[-+]":""},!0),c=e.buildGroupRE(a.separator,function(b){if(!b)return"(?:\\d+)";b=e.escapeString(b);" "==b?b="\\s":"\u00a0"==b&&(b="\\s\\xa0");var c=a.groupSize,d=a.groupSize2;return d?(b="(?:0|[1-9]\\d{0,"+(d-1)+"}(?:["+b+"]\\d{"+d+"})*["+b+"]\\d{"+c+"})",0<c-d?"(?:"+b+"|(?:0|[1-9]\\d{0,"+(c-1)+"}))":b):"(?:0|[1-9]\\d{0,"+(c-1)+"}(?:["+b+"]\\d{"+c+"})*)"},!0);return b+c};return c})},"dojo/currency":function(){define("./_base/array ./_base/lang ./number ./i18n ./i18n!./cldr/nls/currency ./cldr/monetary".split(" "),
function(b,m,h,k,e,c){var n={};m.setObject("dojo.currency",n);n._mixInDefaults=function(a){a=a||{};a.type="currency";var e=k.getLocalization("dojo.cldr","currency",a.locale)||{},d=a.currency,f=c.getData(d);b.forEach(["displayName","symbol","group","decimal"],function(a){f[a]=e[d+"_"+a]});f.fractional=[!0,!1];return m.mixin(f,a)};n.format=function(a,b){return h.format(a,n._mixInDefaults(b))};n.regexp=function(a){return h.regexp(n._mixInDefaults(a))};n.parse=function(a,b){return h.parse(a,n._mixInDefaults(b))};
return n})},"dojo/cldr/monetary":function(){define(["../_base/kernel","../_base/lang"],function(b,m){var h={};m.setObject("dojo.cldr.monetary",h);h.getData=function(b){var e={ADP:0,AFN:0,ALL:0,AMD:0,BHD:3,BIF:0,BYR:0,CLF:0,CLP:0,COP:0,CRC:0,DJF:0,ESP:0,GNF:0,GYD:0,HUF:0,IDR:0,IQD:0,IRR:3,ISK:0,ITL:0,JOD:3,JPY:0,KMF:0,KPW:0,KRW:0,KWD:3,LAK:0,LBP:0,LUF:0,LYD:3,MGA:0,MGF:0,MMK:0,MNT:0,MRO:0,MUR:0,OMR:3,PKR:2,PYG:0,RSD:0,RWF:0,SLL:0,SOS:0,STD:0,SYP:0,TMM:0,TND:3,TRL:0,TZS:0,UGX:0,UZS:0,VND:0,VUV:0,XAF:0,
XOF:0,XPF:0,YER:0,ZMK:0,ZWD:0}[b];b={}[b];"undefined"==typeof e&&(e=2);"undefined"==typeof b&&(b=0);return{places:e,round:b}};return h})},"*now":function(b){b(['dojo/i18n!*preload*dojo/nls/dojo*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])}}});require.boot&&require.apply(null,require.boot);
//# sourceMappingURL=dojo.js.map
define("dojox", function(){
	if(!window["dojox"]){
		window["dojox"] = {};
	}
	return window["dojox"];
});

(function(define){
	// We want to remove this property so people do not
	// think requirejs is in play.
	if(define && define.amd){
		define.oldAmd = define.amd;
		delete define.amd;
	}
})(window.define);
