// Package v1 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from path: /my/api/v1/requestBodyTests/{id}
package v1

import (
	"cto-github.cisco.com/NFV-BU/test-service/pkg/api"
	"encoding/json"
	"github.com/google/uuid"
)

type TestStringRequestBodyRequest struct {
	Id   string `uri:"id" binding:"required,uuid"`
	Body string `json:"-"`
}

func (t *TestStringRequestBodyRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t TestStringRequestBodyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type TestRequestBodyWithAdditionalPropertiesRequest struct {
	Id     string          `uri:"id" binding:"required,uuid"`
	Values json.RawMessage `json:"-"`
}

type PatchTestPathRequest struct {
	Id   string      `uri:"id" binding:"required,uuid"`
	Body []uuid.UUID `json:"-" binding:"omitempty,min=1,dive,uuid"`
}

func (t *PatchTestPathRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t PatchTestPathRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type UpdateServiceStatusRequest struct {
	Id   string              `uri:"id" binding:"required,uuid"`
	Body []api.GenericObject `json:"-" binding:"omitempty,min=1"`
}

func (t *UpdateServiceStatusRequest) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &t.Body)
}

func (t UpdateServiceStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

type PutTestPathRequest struct {
	Id string `uri:"id" binding:"required,uuid"`
	api.GenericObject
}
