// Generated by lanai_cli codegen. DO NOT EDIT
package v1

import (
	"cto-github.cisco.com/NFV-BU/test-service/pkg/api"
)

type DeleteTestPathRequest struct {
	Scope string `uri:"scope" binding:"required,regexA79C5"`
	api.QueryParam
}

type DeleteTestPathResponse struct {
	Id *string `json:"id" binding:"omitempty"`
	api.GenericResponse
}

type TestpathscopeGetRequest struct {
	Scope string `uri:"scope" binding:"required,regexA79C5"`
}
