# information on the service
info:
  app:
    name: "skeleton-service"
    description: "Skeleton Service"
    version: ${application.build.version}
    build-time: ${application.build.build-time}
    attributes:
      displayName: "skeleton-service"
      parent: unknown
      type: unknown

redis:
  addrs: ${spring.redis.host:localhost}:6379
  db: 0

data:
  logging:
    level: warn
    slow-threshold: 5s
  cockroach:
    host: ${db.cockroach.host:localhost}
    port: ${db.cockroach.port:26257}
    sslmode: ${db.cockroach.sslmode:disable}
    username: ${spring.datasource.username:root}
    Password: ${spring.datasource.password:root}
    database: skeleton

tracing:
  enabled: true
  jaeger:
    host: localhost
    port: 6831
  sampler:
    enabled: true
    limit-per-second: 50

server:
  logging:
    default-level: "info"

management:
  enabled: true
  endpoint:
    health:
      show-components: always # authorized | always | never | custom
      show-details: always # authorized | always | never | custom
  security:
    enabled-by-default: false

security:
  keys:
    jwt:
      id: dev
      format: pem
      file: "configs/jwtpubkey.pem"
  jwt:
    key-name: "jwt"
  session:
    idle-timeout: "${security.auth.session-timeout.idle-timeout-seconds:9000}s"
    absolute-timeout: "${security.auth.session-timeout.absolute-timeout-seconds:18000}s"
  timeout-support:
    db-index: 8 # this should have the same value as security.session.db-index on auth service

swagger:
  spec: configs/api-docs-v3.yml
  security:
    sso:
      base-url: ${swagger.security.sso.baseurl:http://localhost:8900/auth}
      client-id: swagger-client

