// Package v1 Generated by lanai-cli codegen.
// Derived from contents in openapi contract, path: /my/api/v1/uuidtest/{id}
package v1

import (
    "context"
    apiv1 "cto-github.cisco.com/NFV-BU/test-service/pkg/api/v1"
    "github.com/cisco-open/go-lanai/pkg/web"
    "github.com/cisco-open/go-lanai/pkg/web/rest"
    "go.uber.org/fx"
)

type UuidtestIdController struct{}

type uuidtestIdControllerDI struct {
	fx.In
}

func NewUuidtestIdController(di uuidtestIdControllerDI) web.Controller {
	return &UuidtestIdController{}
}

func (c *UuidtestIdController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("uuidtest-id-get").
			Get("/api/v1/uuidtest/:id").
			EndpointFunc(c.TestUUIDInPathParam).
			Build(),
	}
}

func (c *UuidtestIdController) TestUUIDInPathParam(ctx context.Context, req apiv1.TestUUIDInPathParamRequest) (interface{}, error) {
	return nil, nil
}
