security:
  idp:
    internal:
      enabled: true
  cors:
    enabled: true
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: ""
    allow-credentials: false
    max-age: 12h
  auth:
    issuer:
      domain: localhost
      protocol: http
      port: 8080
      context-path: ${server.context-path}
      include-port: true
    redirect-whitelist:
      - "internal.vms.com:*/**"
      - "localhost:*/**"
    endpoints:
      authorize: "/v2/authorize"
      token: "/v2/token"
      approval: "/v2/approve"
      check-token: "/v2/check_token"
      tenant-hierarchy: "/v2/tenant_hierarchy"
      error: "/error"
      logout: "/v2/logout"
      user-info: "/v2/userinfo"
      jwk-set: "/v2/jwks"
      saml-metadata: "/metadata"
  cache: #security related cache - currently just for tenant hierarchy data
    db-index: 2
  session:
    cookie:
      domain: ${security.auth.issuer.domain}
    max-concurrent-sessions: 2
    idle-timeout: "2h"
    absolute-timeout: "4h"
    db-index: 8
  timeout-support:
    db-index: ${security.session.db-index}
