// Package v2 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from path: /my/api/v2/testpath
package v2

import (
	"cto-github.cisco.com/NFV-BU/test-service/pkg/api"
)

type GetAllTestPathsRequest struct {
	Id string `form:"id" binding:"required,uuid"`
	api.TestRequest
}
