// Package v2 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from path: /my/api/v2/testArrayUUID
package v2

import (
	"github.com/google/uuid"
)

type TestUUIDInArrayRequest struct {
	Id *[]uuid.UUID `form:"id"`
}
