# This is a shared action for preparing workspace

name: 'Prepare Workspace'
description: 'Prepare the workspace including checking out branch, installing golang, downloading dependencies, etc.'
author: "Livan Du"

# Composite Action
runs:
  using: composite
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v4
      with:
        go-version: '~1.21.5' # go 1.20 has issues: `go test -covermode=atomic` fails when files doesn't have empty line at the end
        # go-version-file: 'go.mod'
        cache-dependency-path: "**/*.sum"
    - name: "Initialize"
      shell: bash
      run: make init SHELL=/bin/bash
