// Package v1 Generated by lanai-cli codegen. DO NOT EDIT
// Derived from path: /skeleton/api/v1/example/friends
package v1

import (
	"cto-github.cisco.com/NFV-BU/go-lanai/examples/skeleton-service/pkg/api"
)

type PostItemsRequest struct {
	api.ExampleRequest
}
