// Package v4 Generated by lanai-cli codegen. DO NOT EDIT
package v4

import (
	"github.com/cisco-open/go-lanai/pkg/bootstrap"
	"github.com/cisco-open/go-lanai/pkg/web"
	"go.uber.org/fx"
)

var Module = &bootstrap.Module{
	Name:       "v4-controller",
	Precedence: bootstrap.AnonymousModulePrecedence,
	Options: []fx.Option{
		web.FxControllerProviders(
			NewTestAPIThatDoesntUseAnyImportsController,
			NewTestRequestBodyUsingARefWithAllOfController,
		),
	},
}
