# This is a shared action for preparing workspace

name: 'Tests & Code Quality'
description: 'Perform tests and code quality analysis. All outputs are written into ./dist/'
author: "Livan Du"

inputs:
  coverpkg:
    description: 'Packages for test coverage calculation. Default to "./pkg/..."'
    default: './pkg/...'
    required: true
  fail_lint:
    description: "Fail when linters report issues. Default to false"
    default: 'false'

# Composite Action
runs:
  using: composite
  steps:
    - name: "Run Tests with Coverage"
      shell: bash
      run: |
        make test report SHELL=/bin/bash ARGS="-covermode atomic -coverpkg ${{ inputs.coverpkg || './pkg/...' }}"
        go tool cover -func=dist/coverage.out -o dist/coverage-func.out

    - name: "Code Quality Analysis"
      shell: bash
      run: make lint SHELL=/bin/bash ARGS="--issues-exit-code ${{ inputs.fail_lint == 'true' && 1 || 0 }}"


