# This is a shared action for preparing workspace

name: 'Tests & Code Quality'
description: 'Perform tests and code quality analysis. All outputs are written into ./dist/'
author: "Livan Du"

inputs:
  coverpkg:
    description: 'Packages for test coverage calculation. Default to "./pkg/..."'
    default: './pkg/...,./test/...'
    required: true
  fail_on_lint_issues:
    description: "Fail when linters report issues. Default to false"
    default: 'false'

# Composite Action
runs:
  using: composite
  steps:
    - name: "Run Tests with Coverage"
      shell: bash
      run: |
        make test report SHELL=/bin/bash GOTESTSUM_FORMAT="github-actions" ARGS="-covermode atomic -coverpkg ${{ inputs.coverpkg || './pkg/...' }}"
        go tool cover -func=dist/coverage.out -o dist/coverage-func.out

    - name: "Code Quality Analysis"
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.59.1
        args: -c=build/ci/golangci.yml --timeout=10m --issues-exit-code=${{ inputs.fail_on_lint_issues == 'true' && 1 || 0 }}
        # if fail_on_lint_issues == true, we assume it's a PR verification
        only-new-issues: ${{ inputs.fail_on_lint_issues == 'true' && 'true' || 'false' }}
        # ~/go/pkg cache conflict with actions/setup-go@v4
        skip-pkg-cache: true


