// Package api Generated by lanai-cli codegen. DO NOT EDIT
// Derived from openapi contract - components
package api

import ()

type ErrorResponse struct {
	Code    *string `json:"code" binding:"required"`
	Message string  `json:"message"`
}

type RequestItem struct {
	FirstName *string `json:"firstName" binding:"required,max=128"`
	LastName  *string `json:"lastName" binding:"required,max=128"`
}

type ResponseItem struct {
	FirstName *string `json:"firstName" binding:"required,max=128"`
	LastName  *string `json:"lastName" binding:"required,max=128"`
}

type ExampleRequest struct {
	RequestItem
}
