integrate:
  security:
    service-name: "authservice"
    failure-back-off: 5m
    guaranteed-validity: 30s
    endpoints:
      password-login: "/v2/token"
      switch-context: "/v2/token"
    client:
      client-id: ${integration.security.client.clientId:nfv-service}
      secret: ${integration.security.client.ClientSecret:nfv-service-secret}
    accounts:
      default:
        username: ${integration.security.accounts.default.username:system}
        password: ${integration.security.accounts.default.password:system}