# This is a basic workflow that is manually triggered

name: PR
run-name: PR Verification triggered by ${{ github.actor }}

env:
  COV_THRESHOLD: '70'

# Controls when the action will run.
on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read
  pull-requests: write
  checks: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - name: "Context"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Checkout Actions"
        uses: actions/checkout@v4
        with:
          # For security reasons, we only uses actions in "main" branch
          ref: ${{ github.event.repository.default_branch }}
          sparse-checkout: .github/actions
          path: .tmp
      - name: "Prepare"
        uses: ./.tmp/.github/actions/prepare
        with:
          branch: ${{ github.head_ref }}
      # Fetch base_ref for later use. We need to detect changed files and only consider test coverage on those files.
      - name: "Prepare PR Verification"
        id: prepare_pr
        uses: ./.tmp/.github/actions/prepare_pr
      - name: "PR Summary"
        env:
          PR_DIFF: ${{ steps.prepare_pr.outputs.diff }}
          CHANGED_GO_FILES: ${{ steps.prepare_pr.outputs.changed_go_files }}
          CHANGED_COV_GO_FILES: ${{ steps.prepare_pr.outputs.changed_cov_go_files }}
          SKIP_COV_CHECK: ${{ steps.prepare_pr.outputs.skip_coverage_check }}
        run: |
          echo "Base Branch: ${{ steps.prepare_pr.outputs.base_ref }}"
          echo "Changed Files(.go): "
          for f in "$CHANGED_GO_FILES"; do
              echo "  $f"
          done
          echo "To-Be-Tested Files(.go): "
          for f in "$CHANGED_COV_GO_FILES"; do
              echo "  $f"
          done
          echo "Skip Coverage Check: $SKIP_COV_CHECK"
          echo "Diff:"
          echo $PR_DIFF
      - name: "Test & Code Quality"
        uses: ./.tmp/.github/actions/verify
        with:
          coverpkg: ${{ steps.prepare_pr.outputs.changed_cov_go_files }}
          fail_on_lint_issues: 'true'
      - name: "PR Test Coverage Report"
        uses: 5monkeys/cobertura-action@master
        with:
          path: dist/cobertura-coverage.xml
          minimum_coverage: 70
          fail_below_threshold: false
          only_changed_files: true
      - name: "Verify PR Test Coverage"
        if: steps.prepare_pr.outputs.skip_coverage_check != 'true'
        shell: bash
        run: |
          go install github.com/PaloAltoNetworks/cov@3.2.0
          cov dist/coverage.out -b ${{ steps.prepare_pr.outputs.base_ref }} \
            --ignore "**/cmd/**" \
            --ignore "**/examples/**" \
            --report-path 'dist/pr-coverage.json' \
            -t ${{ env.COV_THRESHOLD }} -e 1 --write-report
          
          
