# This is a basic workflow that is manually triggered

name: PR Verification
run-name: PR Verification triggered by ${{ github.actor }}

env:
  COV_THRESHOLD: '70'

# Controls when the action will run.
on:
  pull_request:
    branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    name: Verify Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read # Must have this to get actions/checkout@v4 to work (if private repo)
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: "Checkout Actions"
        uses: actions/checkout@v4
        with:
          # For security reasons, we only uses actions in "main" branch
          ref: ${{ github.event.repository.default_branch }}
          sparse-checkout: .github/actions
          path: actions
      - name: "Prepare"
        uses: ./actions/.github/actions/prepare
      - name: "Test & Code Quality"
        uses: ./actions/.github/actions/verify
        with:
          coverpkg: './pkg/...,./test/...'
          fail_lint: 'true'
      - name: "Publish Test Coverage"
        uses: ewjoachim/coverage-comment-action@v1
        if: ${{ !cancelled() }}
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: dist/cobertura-coverage.xml
          BADGE_ENABLED: "true"
          BADGE_FILENAME: dist/coverage-comment-badge.json
          MINIMUM_GREEN: ${{ env.COV_THRESHOLD }}
          MINIMUM_ORANGE: ${{ env.COV_THRESHOLD }}
          # [Advanced] Specify a different template for the comments that will be written on the PR.
          COMMENT_TEMPLATE: ""
          # [Advanced] Additional args to pass to diff cover (one per line)
          DIFF_COVER_ARGS: ""
      - name: "Verify Test Coverage"
        uses: PaloAltoNetworks/cov@3.0.0
        if: ${{ !cancelled() }}
        with:
          cov_mode: coverage
          cov_file: dist/coverage.out
          cov_threshold: ${{ env.COV_THRESHOLD }}
          main_branch: ${{ github.event.repository.default_branch }}
      - name: "Send Test Coverage"
        uses: PaloAltoNetworks/cov@3.0.0
        if: ${{ !cancelled() }}
        with:
          cov_mode: send-status
          workflow_run_id: ${{github.event.workflow_run.id}}
          workflow_head_sha: ${{github.event.workflow_run.head_sha}}


