# This is a basic workflow that is manually triggered

name: Test
run-name: Quality Analysis triggered by ${{ github.actor }}

# Controls when the action will run.
on:
  # PR verification, we disabled it for now
#  pull_request:
#    branches: [ "main" ]
  # Workflow runs when manually triggered using the UI or API.
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        default: 'main'
        required: true
        type: string
      reason:
        description: 'Specify a reason to manually trigger this workflow'
        default: 'Unknown'
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_and_verify:
    name: Tests & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || inputs.branch || 'main' }}
      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"
      - name: "Prepare"
        run: make init SHELL=/bin/bash
      - name: "Run Tests with Coverage"
        run: make test report SHELL=/bin/bash
      - name: "Code Quality Analysis"
        run: make lint SHELL=/bin/bash
      - name: "Code Coverage Report"
        if: ${{ !cancelled() && github.event_name != 'pull_request' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
            filename: dist/cobertura-coverage.xml
            badge: true
            fail_below_min: false
            format: markdown
            output: both
            thresholds: '50 70'
      - name: "Upload Report"
        if: ${{ !cancelled() && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: |
            dist/cobertura-coverage.xml
            dist/junit-report.xml
            code-coverage-results.md
          retention-days: 30
