// Generated by lanai_cli codegen. DO NOT EDIT
package v2

import (
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/bootstrap"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
)

func Use() {
	bootstrap.AddOptions(
		web.FxControllerProviders(
			NewTestpathController,
		),
	)
}
