// Package v2 Generated by lanai_cli codegen. DO NOT EDIT
// Derived from contents in openapi contract, path: /my/api/v2/testpath
package v2

import (
	"context"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web"
	"cto-github.cisco.com/NFV-BU/go-lanai/pkg/web/rest"
	apiv2 "cto-github.cisco.com/NFV-BU/test-service/pkg/api/v2"
	"go.uber.org/fx"
)

type TestpathController struct{}

type testpathControllerDI struct {
	fx.In
}

func NewTestpathController(di testpathControllerDI) web.Controller {
	return &TestpathController{}
}

func (c *TestpathController) Mappings() []web.Mapping {
	return []web.Mapping{
		rest.
			New("testpath-get").
			Get("/api/v2/testpath").
			EndpointFunc(c.GetAllTestPaths).
			Build(),
	}
}

func (c *TestpathController) GetAllTestPaths(ctx context.Context, req apiv2.GetAllTestPathsRequest) (int, interface{}, error) {
	return 501, nil, nil
}
